[build]
  command = "npm run build"
  publish = ".next"

[images]
  remote_images = [
    "https://cuoriplmfomxhguikxcv\\.supabase\\.co/.*",
    "https://hebbkx1anhila5yf\\.public\\.blob\\.vercel-storage\\.com/.*"
  ]

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/favicon*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/og-default.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=604800, s-maxage=604800, immutable"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
    X-Frame-Options = "SAMEORIGIN"
