// Extra 1000+ intent SEO keywords — Her Kingdom Jewelry (herkingdom.shop)
// Additive layer on top of SITE_SEO.allKeywords, STATIC_SEO_KEYWORDS_1000 and
// INTENT_SEO_KEYWORDS. Every phrase here is tuned for high-intent search traffic
// (voice search, AI overviews, question-shaped queries, gift & occasion intent,
// neighborhood-level local SEO) and most phrases explicitly mention the shop
// name "Her Kingdom" and / or the domain "herkingdom.shop" so branded queries
// surface the exact store, not a competitor.

export const INTENT_SEO_KEYWORDS_EXTRA: readonly string[] = [
  // ========== DIRECT BRAND + WEBSITE DISCOVERY ==========
  "herkingdom.shop",
  "herkingdom shop",
  "www.herkingdom.shop",
  "https://herkingdom.shop",
  "herkingdom shop online",
  "herkingdom shop Nairobi",
  "herkingdom shop Kenya",
  "herkingdom shop jewelry",
  "herkingdom shop necklaces",
  "herkingdom shop earrings",
  "herkingdom shop bracelets",
  "herkingdom shop watches",
  "herkingdom shop handbags",
  "herkingdom shop gift packages",
  "herkingdom shop perfume",
  "herkingdom shop sunglasses",
  "herkingdom shop new arrivals",
  "herkingdom shop offers",
  "herkingdom shop sale",
  "herkingdom shop delivery",
  "herkingdom shop checkout",
  "herkingdom shop login",
  "herkingdom shop wishlist",
  "herkingdom shop blog",
  "herkingdom shop reviews",
  "herkingdom shop WhatsApp",
  "herkingdom shop contact",
  "open herkingdom.shop",
  "visit herkingdom.shop",
  "go to herkingdom.shop",
  "log in to herkingdom.shop",
  "order from herkingdom.shop",
  "buy from herkingdom.shop",
  "shop on herkingdom.shop",
  "browse herkingdom.shop",
  "sign up on herkingdom.shop",
  "herkingdom.shop login",
  "herkingdom.shop checkout",
  "herkingdom.shop tracking",
  "herkingdom.shop account",
  "herkingdom.shop catalog",
  "herkingdom.shop lookbook",
  "herkingdom.shop price list",
  "herkingdom.shop prices Kenya",
  "herkingdom.shop reviews Kenya",
  "herkingdom.shop testimonials",
  "herkingdom.shop instagram",
  "herkingdom.shop tiktok",
  "herkingdom.shop WhatsApp number",
  "herkingdom.shop delivery Nairobi",
  "herkingdom.shop delivery Kenya",

  // ========== "HER KINGDOM" BRANDED LONG-TAIL ==========
  // Mirrors the real navbar + footer on herkingdom.shop:
  // Navbar: Home, dynamic category links (/shop?category=SLUG), Track My Order,
  // Search, Wishlist, Cart / Checkout, All Categories dropdown, Instagram, TikTok,
  // WhatsApp, phone contact.
  // Footer quick links: Shop All, New Arrivals, On Offer, Blog & Articles,
  // Track My Order, Delivery Locations, Necklaces, Bracelets, Earrings,
  // Payments Policy, Privacy Policy, Terms of Service, Refund Policy, Sitemap.
  "Her Kingdom jewelry shop herkingdom.shop",
  "Her Kingdom online store herkingdom.shop",
  "Her Kingdom jewelry Nairobi herkingdom.shop",
  "Her Kingdom Kenya herkingdom.shop",
  "Her Kingdom website link",
  "Her Kingdom website address",
  "Her Kingdom official website",
  "Her Kingdom official store",
  "Her Kingdom official online shop Kenya",
  "Her Kingdom site Kenya",
  "Her Kingdom site Nairobi",
  "Her Kingdom URL",
  // Home
  "Her Kingdom homepage",
  "Her Kingdom home page Kenya",
  "Her Kingdom landing page Kenya",
  // Shop all
  "Her Kingdom shop all page",
  "Her Kingdom shop page",
  "Her Kingdom shop online Kenya",
  "Her Kingdom browse all jewelry",
  // Category links from the dynamic navbar + footer quick links
  "Her Kingdom necklaces Kenya",
  "Her Kingdom necklaces Nairobi",
  "Her Kingdom bracelets Kenya",
  "Her Kingdom bracelets Nairobi",
  "Her Kingdom earrings Kenya",
  "Her Kingdom earrings Nairobi",
  "Her Kingdom watches Kenya",
  "Her Kingdom handbags Kenya",
  "Her Kingdom sunglasses Kenya",
  "Her Kingdom perfume Kenya",
  "Her Kingdom gift packages Kenya",
  "Her Kingdom rings Kenya",
  "Her Kingdom anklets Kenya",
  "Her Kingdom jewelry sets Kenya",
  "Her Kingdom category page necklaces",
  "Her Kingdom category page bracelets",
  "Her Kingdom category page earrings",
  // /shop/[collection] — men / women / babyshop pages that exist
  "Her Kingdom shop women page",
  "Her Kingdom shop men page",
  "Her Kingdom shop babyshop page",
  "Her Kingdom women jewelry Kenya",
  "Her Kingdom men jewelry Kenya",
  "Her Kingdom babyshop Kenya",
  // Shop filters exposed from the footer
  "Her Kingdom new arrivals page",
  "Her Kingdom new arrivals Kenya",
  "Her Kingdom on offer page",
  "Her Kingdom offers page Kenya",
  "Her Kingdom sale page Kenya",
  // Search (navbar)
  "Her Kingdom search bar",
  "Her Kingdom search page",
  "Her Kingdom search jewelry Kenya",
  // Wishlist (navbar)
  "Her Kingdom wishlist page",
  "Her Kingdom save jewelry to wishlist",
  // Cart & checkout (cart drawer + /checkout)
  "Her Kingdom cart page",
  "Her Kingdom cart drawer",
  "Her Kingdom checkout page",
  "Her Kingdom secure checkout Kenya",
  // Auth pages (/auth/login, /auth/register)
  "Her Kingdom login page",
  "Her Kingdom register page",
  "Her Kingdom create account Kenya",
  // Track order (navbar + footer)
  "Her Kingdom track my order page",
  "Her Kingdom track order Kenya",
  "Her Kingdom order tracking Nairobi",
  // Delivery locations (footer)
  "Her Kingdom delivery locations page",
  "Her Kingdom delivery page Kenya",
  "Her Kingdom delivery zones Nairobi",
  // Blog & articles (footer)
  "Her Kingdom blog and articles",
  "Her Kingdom blog page Kenya",
  "Her Kingdom jewelry articles Kenya",
  "Her Kingdom jewelry guides Kenya",
  // Policies (footer)
  "Her Kingdom payments policy page",
  "Her Kingdom privacy policy page",
  "Her Kingdom terms of service page",
  "Her Kingdom refund policy page",
  // Contact surfaces (navbar social + footer contact)
  "Her Kingdom Instagram page",
  "Her Kingdom TikTok page",
  "Her Kingdom WhatsApp order",
  "Her Kingdom phone contact Kenya",
  "Her Kingdom email Kenya",
  // Sitemap (newly linked in the footer)
  "Her Kingdom sitemap",
  "herkingdom.shop sitemap",
  "Her Kingdom site map Kenya",
  // Catalogue / best sellers framings that map to /shop filters
  "Her Kingdom jewelry catalogue online",
  "Her Kingdom jewelry collection 2026",
  "Her Kingdom best sellers 2026",
  "Her Kingdom trending pieces 2026",
  "Her Kingdom top picks Kenya",
  "Her Kingdom featured jewelry",

  // ========== LEGITIMACY, REVIEWS, TRUST (BRAND-LED) ==========
  "is Her Kingdom legit Kenya",
  "is Her Kingdom legit Nairobi",
  "is herkingdom.shop legit",
  "is herkingdom.shop real",
  "is herkingdom.shop safe to order",
  "is Her Kingdom safe to buy from",
  "is Her Kingdom real jewelry",
  "is Her Kingdom trusted in Kenya",
  "Her Kingdom reviews Nairobi",
  "Her Kingdom customer reviews Kenya",
  "Her Kingdom testimonials Kenya",
  "Her Kingdom Google reviews",
  "Her Kingdom Trustpilot reviews",
  "Her Kingdom Instagram reviews",
  "Her Kingdom TikTok reviews Kenya",
  "Her Kingdom rating Kenya",
  "Her Kingdom feedback Kenya",
  "Her Kingdom experience Kenya",
  "Her Kingdom complaints Kenya",
  "Her Kingdom return experience Kenya",
  "how trusted is Her Kingdom",
  "how genuine is Her Kingdom jewelry",
  "are Her Kingdom earrings hypoallergenic",
  "does Her Kingdom tarnish",
  "does Her Kingdom jewelry fade",
  "does Her Kingdom ship to Kenya",
  "does Her Kingdom ship to diaspora",
  "does Her Kingdom accept M-Pesa",
  "does Her Kingdom accept cash on delivery",
  "does Her Kingdom deliver same day",
  "does Her Kingdom have a physical shop",
  "Her Kingdom customer service Kenya",
  "Her Kingdom support WhatsApp Kenya",
  "Her Kingdom response time Kenya",
  "Her Kingdom delivery experience Kenya",
  "Her Kingdom unboxing Kenya",
  "Her Kingdom packaging Kenya",
  "Her Kingdom quality review Kenya",

  // ========== VOICE SEARCH / CONVERSATIONAL ==========
  "hey Google where can I buy jewelry in Nairobi",
  "hey Siri where to buy jewelry in Kenya",
  "Alexa where is the best jewelry shop in Nairobi",
  "tell me the best jewelry shop in Nairobi",
  "show me a jewelry shop near me in Nairobi",
  "find a jewelry shop that delivers in Nairobi",
  "find an online jewelry shop in Kenya",
  "open the best jewelry site in Kenya",
  "who sells hypoallergenic jewelry in Kenya",
  "who sells affordable jewelry in Nairobi",
  "who sells matching jewelry sets in Nairobi",
  "who delivers jewelry same day in Nairobi",
  "what is the best jewelry shop in Nairobi",
  "what is herkingdom.shop",
  "what is Her Kingdom shop",
  "who is Her Kingdom Kenya",
  "what does Her Kingdom sell",
  "what does herkingdom.shop sell",
  "what kind of jewelry does Her Kingdom sell",
  "what does Her Kingdom Nairobi stock",
  "how do I order from Her Kingdom",
  "how do I buy from herkingdom.shop",
  "how do I track my Her Kingdom order",
  "how do I contact Her Kingdom",
  "how do I pay Her Kingdom with M-Pesa",
  "how do I return a Her Kingdom item",
  "how long does Her Kingdom take to deliver",
  "how much is delivery at Her Kingdom",
  "how much is a necklace at Her Kingdom",
  "how much is a ring at Her Kingdom",
  "how much is a watch at Her Kingdom",
  "how much is a gift package at Her Kingdom",
  "how much does Her Kingdom charge for delivery",
  "when does Her Kingdom restock",
  "when does Her Kingdom have a sale",
  "when does Her Kingdom do Black Friday Kenya",
  "when does Her Kingdom close orders",
  "when does Her Kingdom open",
  "can I order Her Kingdom via WhatsApp",
  "can I order Her Kingdom from Mombasa",
  "can I order Her Kingdom from Kisumu",
  "can I order Her Kingdom from abroad",
  "can I gift wrap at Her Kingdom",
  "can I add a gift note at Her Kingdom",
  "can I get a receipt from Her Kingdom",
  "can I pay on delivery at Her Kingdom",
  "can I exchange jewelry at Her Kingdom",
  "can I refund at Her Kingdom",
  "why shop at Her Kingdom",
  "why is Her Kingdom the best jewelry shop in Nairobi",
  "why choose herkingdom.shop",

  // ========== AI OVERVIEW / PEOPLE ALSO ASK ==========
  "what is the best online jewelry store in Kenya",
  "which is the best jewelry shop in Nairobi right now",
  "what are the top jewelry brands in Kenya 2026",
  "which jewelry shop delivers fastest in Nairobi",
  "which jewelry shop has the best prices in Kenya",
  "which jewelry shop is best for bridal sets in Nairobi",
  "which jewelry shop is best for gifts in Nairobi",
  "which jewelry shop is best for men's watches in Kenya",
  "which jewelry store does M-Pesa in Kenya",
  "which jewelry brand is most trusted in Nairobi",
  "which Nairobi jewelry shop ships to diaspora",
  "which Kenyan jewelry store ships internationally",
  "what is the most reviewed jewelry shop in Nairobi",
  "what is the most affordable jewelry shop in Nairobi",
  "what is the newest jewelry shop in Nairobi",
  "what is Her Kingdom famous for",
  "what are the top 5 jewelry shops in Nairobi",
  "what are the top 10 online jewelry stores in Kenya",
  "top rated jewelry shop in Nairobi",
  "most popular jewelry shop in Nairobi",
  "most trusted online jewelry shop in Kenya",
  "best reviewed jewelry shop in Kenya",
  "best Instagram jewelry shop in Nairobi",
  "best TikTok jewelry shop in Nairobi",
  "best WhatsApp jewelry shop in Nairobi",
  "best Kenyan jewelry brand 2026",
  "best Nairobi jewelry brand for weddings",
  "best Nairobi jewelry brand for everyday",
  "best Kenyan jewelry brand for men",
  "best Kenyan jewelry brand for students",
  "best Kenyan jewelry brand for moms",

  // ========== HER KINGDOM VS COMPETITORS ==========
  "Her Kingdom vs Zaida Jewelry",
  "Her Kingdom vs Jumia jewelry Kenya",
  "Her Kingdom vs Kilimall jewelry Kenya",
  "Her Kingdom vs SHEIN jewelry Kenya",
  "Her Kingdom vs Ajio jewelry Kenya",
  "Her Kingdom vs Amazon jewelry Kenya",
  "Her Kingdom vs high street jewelry Nairobi",
  "Her Kingdom vs Instagram shops Nairobi",
  "Her Kingdom vs Sarit Centre jewelry",
  "Her Kingdom vs Village Market jewelry",
  "Her Kingdom vs Westgate jewelry",
  "Her Kingdom or Jumia which is better jewelry",
  "Her Kingdom or SHEIN for jewelry Kenya",
  "is Her Kingdom cheaper than Jumia jewelry",
  "is Her Kingdom cheaper than SHEIN jewelry Kenya",
  "is Her Kingdom faster than Jumia delivery Kenya",
  "is Her Kingdom better than SHEIN for hypoallergenic earrings",
  "is Her Kingdom better quality than Jumia jewelry",
  "does Her Kingdom beat SHEIN prices in Kenya",
  "Her Kingdom alternative in Nairobi",
  "Her Kingdom competitor in Kenya",
  "shops similar to Her Kingdom in Nairobi",
  "shops like Her Kingdom Kenya",
  "online jewelry shops like herkingdom.shop",
  "cheaper alternatives to Her Kingdom",
  "premium alternatives to Her Kingdom",
  "is Her Kingdom the cheapest jewelry shop in Nairobi",
  "is Her Kingdom the best value jewelry shop in Kenya",
  "why Her Kingdom over other Nairobi jewelry shops",
  "Her Kingdom vs import jewelry Kenya",

  // ========== BUYER JOURNEY / INTENT FUNNEL ==========
  "just browsing jewelry Nairobi",
  "window shopping jewelry Nairobi online",
  "researching jewelry shops in Nairobi",
  "comparing jewelry prices in Nairobi",
  "first time buying jewelry online Kenya",
  "first time ordering from Her Kingdom",
  "ready to buy jewelry online in Kenya",
  "ready to order jewelry in Nairobi",
  "where to start buying jewelry in Kenya",
  "beginner jewelry shopping Kenya",
  "help me pick jewelry Nairobi",
  "help me choose a gift on herkingdom.shop",
  "help me find earrings in Nairobi",
  "recommend a jewelry shop in Nairobi",
  "recommend a jewelry set for a wedding in Kenya",
  "recommend a gift for my girlfriend Nairobi",
  "recommend a gift for my wife Kenya",
  "recommend a gift for my mom Kenya",
  "recommend a gift for my daughter Kenya",
  "recommend a gift for my sister Nairobi",
  "suggest a jewelry shop in Nairobi",
  "suggest an outfit with gold earrings Kenya",
  "suggest a chain for a man in Nairobi",
  "suggest a bracelet for a student Kenya",
  "advice on buying jewelry online Kenya",
  "guide to buying jewelry in Nairobi",
  "first jewelry piece guide Kenya",
  "step by step how to order from Her Kingdom",
  "step by step how to pay Her Kingdom M-Pesa",
  "step by step how to track Her Kingdom order",

  // ========== GIFT RECIPIENT INTENT (DETAILED) ==========
  "gift for my girlfriend Nairobi herkingdom.shop",
  "gift for my wife Kenya Her Kingdom",
  "gift for my mom Nairobi Her Kingdom",
  "gift for my stepmom Nairobi",
  "gift for my mother in law Nairobi",
  "gift for my sister Nairobi herkingdom.shop",
  "gift for my little sister Kenya",
  "gift for my big sister Kenya",
  "gift for my cousin Nairobi",
  "gift for my best friend Nairobi Her Kingdom",
  "gift for my bestie Nairobi",
  "gift for my bridesmaid Kenya Her Kingdom",
  "gift for my maid of honor Nairobi",
  "gift for my aunt Nairobi",
  "gift for my grandma Nairobi",
  "gift for my daughter Nairobi Her Kingdom",
  "gift for my teen daughter Kenya",
  "gift for my 16 year old Kenya",
  "gift for my 18 year old Kenya",
  "gift for my 21 year old Kenya",
  "gift for my 25 year old Kenya",
  "gift for my 30 year old Kenya",
  "gift for my boss lady Nairobi",
  "gift for my colleague Kenya",
  "gift for my assistant Nairobi",
  "gift for my team Kenya",
  "gift for my client Nairobi",
  "gift for her graduation Nairobi",
  "gift for her promotion Nairobi",
  "gift for her new job Nairobi",
  "gift for her baby shower Nairobi",
  "gift for her bridal shower Nairobi",
  "gift for her hen night Nairobi",
  "gift for her engagement Nairobi",
  "gift for her wedding Nairobi",
  "gift for her honeymoon Kenya",
  "gift for her push present Kenya",
  "gift for her anniversary month Kenya",
  "gift for her just because Nairobi",
  "apology gift for her Nairobi",
  "welcome back gift for her Nairobi",
  "thank you gift for her Nairobi",
  "surprise gift for her Nairobi",
  "long distance gift for her Kenya",
  "gift for him from Her Kingdom",
  "gift for my boyfriend Nairobi Her Kingdom",
  "gift for my husband Nairobi Her Kingdom",
  "gift for my fiance Kenya",
  "gift for my dad Nairobi",
  "gift for my brother Nairobi",
  "gift for my son Kenya",
  "matching gift for couples Nairobi Her Kingdom",

  // ========== OCCASION-SPECIFIC (DEEPER) ==========
  "jewelry for kitchen party Nairobi",
  "jewelry for ruracio Kenya",
  "jewelry for traditional wedding Kenya",
  "jewelry for white wedding Kenya",
  "jewelry for civil wedding Kenya",
  "jewelry for dowry ceremony Kenya",
  "jewelry for engagement party Nairobi",
  "jewelry for introduction ceremony Kenya",
  "jewelry for come we stay Kenya",
  "jewelry for baby shower Nairobi",
  "jewelry for baby naming Kenya",
  "jewelry for baptism gift Kenya",
  "jewelry for confirmation gift Kenya",
  "jewelry for first communion Kenya",
  "jewelry for ruracio attire Kenya",
  "jewelry for ankara dress Kenya",
  "jewelry for kitenge dress Nairobi",
  "jewelry for kikoi Kenya",
  "jewelry for leso Kenya",
  "jewelry for dera Kenya",
  "jewelry for hijab Kenya",
  "jewelry for abaya Kenya",
  "jewelry for Maasai wedding Kenya",
  "jewelry for Kikuyu wedding Kenya",
  "jewelry for Luo wedding Kenya",
  "jewelry for Kamba wedding Kenya",
  "jewelry for Kalenjin wedding Kenya",
  "jewelry for Luhya wedding Kenya",
  "jewelry for Swahili wedding Kenya",
  "jewelry for Nikah Kenya",
  "jewelry for Eid outfit Nairobi",
  "jewelry for Diwali outfit Nairobi",
  "jewelry for graduation gown Kenya",
  "jewelry for prom Kenya",
  "jewelry for school leavers ball Kenya",
  "jewelry for university graduation Kenya",
  "jewelry for corporate event Nairobi",
  "jewelry for gala night Nairobi",
  "jewelry for awards night Nairobi",
  "jewelry for pitch deck day Nairobi",
  "jewelry for church Kenya",
  "jewelry for choir Kenya",
  "jewelry for harambee Kenya",
  "jewelry for funeral Kenya",
  "jewelry for memorial service Kenya",
  "jewelry for birthday photoshoot Nairobi",
  "jewelry for maternity shoot Nairobi",
  "jewelry for family photos Kenya",
  "jewelry for engagement shoot Nairobi",
  "jewelry for pre wedding shoot Nairobi",
  "jewelry for boudoir shoot Nairobi",
  "jewelry for birthday dinner Nairobi",
  "jewelry for dinner date Nairobi",
  "jewelry for brunch Nairobi",
  "jewelry for rooftop dinner Nairobi",
  "jewelry for Nairobi nightlife",
  "jewelry for club Nairobi",
  "jewelry for festival Kenya",
  "jewelry for Koroga Festival Kenya",
  "jewelry for Blankets and Wine Kenya",
  "jewelry for Nairobi Jazz Festival",

  // ========== STYLE ARCHETYPES / AESTHETIC ==========
  "soft girl jewelry Nairobi Her Kingdom",
  "clean girl jewelry Kenya Her Kingdom",
  "quiet luxury jewelry Kenya herkingdom.shop",
  "old money aesthetic jewelry Nairobi",
  "coastal granddaughter jewelry Kenya",
  "baddie jewelry Nairobi",
  "cottagecore jewelry Kenya",
  "fairycore jewelry Kenya",
  "coquette jewelry Kenya Her Kingdom",
  "dark academia jewelry Nairobi",
  "light academia jewelry Nairobi",
  "y2k revival jewelry Kenya",
  "90s jewelry Nairobi",
  "2000s jewelry Kenya",
  "afrofuturism jewelry Nairobi",
  "afrobeats jewelry Kenya",
  "amapiano jewelry Kenya",
  "gengetone jewelry Nairobi",
  "street style jewelry Nairobi Her Kingdom",
  "editorial jewelry Nairobi",
  "minimal cool girl jewelry Kenya",
  "it girl jewelry Nairobi",
  "CEO girly jewelry Nairobi",
  "founder girly jewelry Kenya",
  "girl boss jewelry Kenya",
  "power lady jewelry Nairobi",
  "hot girl summer jewelry Kenya",
  "Detty December jewelry Nairobi Her Kingdom",
  "festive season jewelry Kenya",
  "beach day jewelry Mombasa Her Kingdom",
  "Diani jewelry Kenya",
  "Watamu jewelry Kenya",
  "Lamu jewelry Kenya",
  "safari outfit jewelry Kenya",
  "Maasai Mara safari jewelry Kenya",
  "weekend getaway jewelry Kenya",
  "Nanyuki getaway jewelry Kenya",
  "Naivasha day trip jewelry Kenya",
  "road trip jewelry Kenya",
  "travel jewelry Kenya",
  "airport outfit jewelry Nairobi",
  "flight day jewelry Kenya",
  "dubai trip jewelry Kenya",
  "international travel jewelry Kenya",

  // ========== BUDGET & PRICE TIERS ==========
  "jewelry under KSh 500 Nairobi Her Kingdom",
  "jewelry under KSh 1000 Nairobi Her Kingdom",
  "jewelry under KSh 1500 Nairobi",
  "jewelry under KSh 2000 Kenya Her Kingdom",
  "jewelry under KSh 2500 Nairobi",
  "jewelry under KSh 3000 Kenya Her Kingdom",
  "jewelry under KSh 4000 Nairobi",
  "jewelry under KSh 5000 Kenya Her Kingdom",
  "jewelry under KSh 6000 Nairobi",
  "jewelry under KSh 7000 Kenya",
  "jewelry under KSh 8000 Nairobi",
  "jewelry under KSh 10000 Kenya Her Kingdom",
  "jewelry under KSh 15000 Kenya",
  "jewelry between KSh 1000 and KSh 3000 Nairobi",
  "jewelry between KSh 3000 and KSh 5000 Kenya",
  "jewelry between KSh 5000 and KSh 10000 Kenya",
  "cheapest earrings at Her Kingdom",
  "cheapest necklace at Her Kingdom",
  "cheapest bracelet at Her Kingdom",
  "cheapest watch at Her Kingdom",
  "most expensive jewelry at Her Kingdom",
  "premium jewelry at Her Kingdom",
  "affordable statement necklace Kenya Her Kingdom",
  "affordable hoop earrings Kenya Her Kingdom",
  "affordable gold plated jewelry Nairobi Her Kingdom",
  "affordable bridal set Kenya Her Kingdom",
  "affordable matching set Kenya Her Kingdom",
  "bulk order jewelry Nairobi Her Kingdom",
  "wholesale jewelry Kenya Her Kingdom",
  "reseller jewelry Kenya Her Kingdom",

  // ========== NAIROBI NEIGHBORHOOD LOCAL SEO (DEEPER) ==========
  "jewelry shop Westlands Her Kingdom",
  "jewelry shop Kilimani Her Kingdom",
  "jewelry shop Karen Her Kingdom",
  "jewelry shop Lavington Her Kingdom",
  "jewelry shop Kileleshwa Her Kingdom",
  "jewelry shop Runda Her Kingdom",
  "jewelry shop Muthaiga Her Kingdom",
  "jewelry shop Gigiri Her Kingdom",
  "jewelry shop Parklands Her Kingdom",
  "jewelry shop Spring Valley Her Kingdom",
  "jewelry shop Riverside Her Kingdom",
  "jewelry shop Upper Hill Her Kingdom",
  "jewelry shop Hurlingham Her Kingdom",
  "jewelry shop South B Her Kingdom",
  "jewelry shop South C Her Kingdom",
  "jewelry shop Langata Her Kingdom",
  "jewelry shop Ngong Road Her Kingdom",
  "jewelry shop Kibera Her Kingdom",
  "jewelry shop Kasarani Her Kingdom",
  "jewelry shop Roysambu Her Kingdom",
  "jewelry shop Thome Her Kingdom",
  "jewelry shop Garden City Her Kingdom",
  "jewelry shop Ruaraka Her Kingdom",
  "jewelry shop Kariobangi Her Kingdom",
  "jewelry shop Eastleigh Her Kingdom",
  "jewelry shop Umoja Her Kingdom",
  "jewelry shop Buruburu Her Kingdom",
  "jewelry shop Donholm Her Kingdom",
  "jewelry shop Embakasi Her Kingdom",
  "jewelry shop Syokimau Her Kingdom",
  "jewelry shop Mlolongo Her Kingdom",
  "jewelry shop Kitengela Her Kingdom",
  "jewelry shop Athi River Her Kingdom",
  "jewelry shop Ruiru Her Kingdom",
  "jewelry shop Juja Her Kingdom",
  "jewelry shop Thika Her Kingdom",
  "jewelry shop Kiambu Her Kingdom",
  "jewelry shop Limuru Her Kingdom",
  "jewelry shop Banana Hill Her Kingdom",
  "jewelry shop Ruaka Her Kingdom",
  "jewelry shop Kikuyu Her Kingdom",
  "jewelry shop Ngong Her Kingdom",
  "jewelry shop Rongai Her Kingdom",
  "jewelry shop Karen Hardy Her Kingdom",
  "jewelry shop Galleria Her Kingdom",
  "jewelry shop Junction Mall Her Kingdom",
  "jewelry shop Sarit Centre Her Kingdom",
  "jewelry shop Westgate Her Kingdom",
  "jewelry shop Village Market Her Kingdom",
  "jewelry shop Two Rivers Her Kingdom",
  "jewelry shop Yaya Centre Her Kingdom",
  "jewelry shop Prestige Plaza Her Kingdom",
  "jewelry shop Capital Centre Her Kingdom",
  "jewelry shop TRM Her Kingdom",
  "jewelry shop Greenspan Her Kingdom",
  "jewelry shop Waterfront Karen Her Kingdom",
  "jewelry shop Ridgeways Her Kingdom",
  "jewelry shop Kileleshwa Ring Road Her Kingdom",

  // ========== JEWELRY DELIVERY BY NEIGHBORHOOD ==========
  "jewelry delivery Westlands Her Kingdom",
  "jewelry delivery Kilimani Her Kingdom",
  "jewelry delivery Karen Her Kingdom",
  "jewelry delivery Lavington Her Kingdom",
  "jewelry delivery Kileleshwa Her Kingdom",
  "jewelry delivery Runda Her Kingdom",
  "jewelry delivery Muthaiga Her Kingdom",
  "jewelry delivery Gigiri Her Kingdom",
  "jewelry delivery Parklands Her Kingdom",
  "jewelry delivery Upper Hill Her Kingdom",
  "jewelry delivery Hurlingham Her Kingdom",
  "jewelry delivery South B Her Kingdom",
  "jewelry delivery South C Her Kingdom",
  "jewelry delivery Langata Her Kingdom",
  "jewelry delivery Ngong Road Her Kingdom",
  "jewelry delivery Kasarani Her Kingdom",
  "jewelry delivery Roysambu Her Kingdom",
  "jewelry delivery Garden City Her Kingdom",
  "jewelry delivery Ruaraka Her Kingdom",
  "jewelry delivery Eastleigh Her Kingdom",
  "jewelry delivery Umoja Her Kingdom",
  "jewelry delivery Buruburu Her Kingdom",
  "jewelry delivery Donholm Her Kingdom",
  "jewelry delivery Embakasi Her Kingdom",
  "jewelry delivery Syokimau Her Kingdom",
  "jewelry delivery Mlolongo Her Kingdom",
  "jewelry delivery Kitengela Her Kingdom",
  "jewelry delivery Athi River Her Kingdom",
  "jewelry delivery Ruiru Her Kingdom",
  "jewelry delivery Juja Her Kingdom",
  "jewelry delivery Thika Her Kingdom",
  "jewelry delivery Kiambu Her Kingdom",
  "jewelry delivery Limuru Her Kingdom",
  "jewelry delivery Ruaka Her Kingdom",
  "jewelry delivery Kikuyu Her Kingdom",
  "jewelry delivery Ngong Her Kingdom",
  "jewelry delivery Rongai Her Kingdom",
  "jewelry delivery JKIA Her Kingdom",
  "jewelry delivery Wilson Airport Her Kingdom",
  "jewelry delivery CBD Nairobi Her Kingdom",

  // ========== KENYA CITY LEVEL + REGIONS ==========
  "jewelry shop Mombasa Her Kingdom",
  "jewelry shop Nyali Her Kingdom",
  "jewelry shop Bamburi Her Kingdom",
  "jewelry shop Diani Her Kingdom",
  "jewelry shop Malindi Her Kingdom",
  "jewelry shop Watamu Her Kingdom",
  "jewelry shop Lamu Her Kingdom",
  "jewelry shop Kisumu Her Kingdom",
  "jewelry shop Kakamega Her Kingdom",
  "jewelry shop Kisii Her Kingdom",
  "jewelry shop Bungoma Her Kingdom",
  "jewelry shop Busia Her Kingdom",
  "jewelry shop Migori Her Kingdom",
  "jewelry shop Homa Bay Her Kingdom",
  "jewelry shop Nakuru Her Kingdom",
  "jewelry shop Naivasha Her Kingdom",
  "jewelry shop Nanyuki Her Kingdom",
  "jewelry shop Nyeri Her Kingdom",
  "jewelry shop Meru Her Kingdom",
  "jewelry shop Embu Her Kingdom",
  "jewelry shop Machakos Her Kingdom",
  "jewelry shop Kitui Her Kingdom",
  "jewelry shop Makueni Her Kingdom",
  "jewelry shop Voi Her Kingdom",
  "jewelry shop Taita Her Kingdom",
  "jewelry shop Eldoret Her Kingdom",
  "jewelry shop Kitale Her Kingdom",
  "jewelry shop Kericho Her Kingdom",
  "jewelry shop Bomet Her Kingdom",
  "jewelry shop Narok Her Kingdom",
  "jewelry shop Kajiado Her Kingdom",
  "jewelry shop Isiolo Her Kingdom",
  "jewelry shop Garissa Her Kingdom",
  "jewelry shop Lodwar Her Kingdom",
  "jewelry shop Marsabit Her Kingdom",
  "jewelry shop Kilifi Her Kingdom",
  "jewelry shop Nyandarua Her Kingdom",
  "jewelry shop Murang'a Her Kingdom",
  "jewelry delivery Mombasa Her Kingdom",
  "jewelry delivery Kisumu Her Kingdom",
  "jewelry delivery Nakuru Her Kingdom",
  "jewelry delivery Eldoret Her Kingdom",
  "jewelry delivery Nanyuki Her Kingdom",
  "jewelry delivery Nyeri Her Kingdom",
  "jewelry delivery Meru Her Kingdom",
  "jewelry delivery Malindi Her Kingdom",
  "jewelry delivery Diani Her Kingdom",
  "jewelry delivery Kisii Her Kingdom",
  "jewelry delivery Machakos Her Kingdom",
  "jewelry delivery Kitui Her Kingdom",
  "jewelry delivery Kakamega Her Kingdom",
  "jewelry delivery Kericho Her Kingdom",

  // ========== DIASPORA / INTERNATIONAL ==========
  "Kenyan jewelry shop that ships to UK Her Kingdom",
  "Kenyan jewelry shop that ships to USA Her Kingdom",
  "Kenyan jewelry shop that ships to Canada Her Kingdom",
  "Kenyan jewelry shop that ships to Germany Her Kingdom",
  "Kenyan jewelry shop that ships to Dubai Her Kingdom",
  "Kenyan jewelry shop that ships to UAE Her Kingdom",
  "Kenyan jewelry shop that ships to Qatar Her Kingdom",
  "Kenyan jewelry shop that ships to Saudi Arabia Her Kingdom",
  "Kenyan jewelry shop that ships to Australia Her Kingdom",
  "Kenyan jewelry shop that ships to South Africa Her Kingdom",
  "Kenyan jewelry shop that ships to Nigeria Her Kingdom",
  "Kenyan jewelry shop that ships to Uganda Her Kingdom",
  "Kenyan jewelry shop that ships to Tanzania Her Kingdom",
  "Kenyan jewelry shop that ships to Rwanda Her Kingdom",
  "Kenyan jewelry shop that ships to Ethiopia Her Kingdom",
  "Kenyan jewelry shop that ships to Sweden Her Kingdom",
  "Kenyan jewelry shop that ships to Norway Her Kingdom",
  "send jewelry to Kenya from abroad Her Kingdom",
  "send jewelry to mom in Nairobi Her Kingdom",
  "send flowers and jewelry to Nairobi Her Kingdom",
  "gift to Nairobi from abroad Her Kingdom",
  "gift to Kenya from UK Her Kingdom",
  "gift to Kenya from USA Her Kingdom",
  "diaspora gift Her Kingdom Nairobi",
  "order from Her Kingdom while abroad",
  "Her Kingdom international delivery",
  "Her Kingdom diaspora orders",

  // ========== SEASONAL / HOLIDAY 2026 ==========
  "Valentines Day 2026 jewelry Nairobi Her Kingdom",
  "Valentines Day 2026 gift for her Kenya Her Kingdom",
  "Valentines Day 2026 last minute gift Nairobi Her Kingdom",
  "Mothers Day 2026 jewelry Kenya Her Kingdom",
  "Mothers Day 2026 gift Kenya Her Kingdom",
  "Fathers Day 2026 jewelry Kenya Her Kingdom",
  "Easter 2026 gift Kenya Her Kingdom",
  "Ramadan 2026 Eid gift Kenya Her Kingdom",
  "Eid al Fitr 2026 jewelry Kenya Her Kingdom",
  "Eid al Adha 2026 gift Kenya Her Kingdom",
  "Christmas 2026 jewelry Kenya Her Kingdom",
  "Christmas 2026 gift Nairobi Her Kingdom",
  "Boxing Day 2026 jewelry Kenya Her Kingdom",
  "New Year 2026 jewelry Kenya Her Kingdom",
  "Black Friday 2026 Kenya Her Kingdom",
  "Cyber Monday 2026 Kenya Her Kingdom",
  "Jamhuri Day 2026 outfit jewelry Kenya Her Kingdom",
  "Mashujaa Day 2026 jewelry Kenya Her Kingdom",
  "Madaraka Day 2026 jewelry Kenya Her Kingdom",
  "International Women's Day 2026 gift Kenya Her Kingdom",
  "Galentines Day 2026 gift Nairobi Her Kingdom",
  "Women's Month 2026 jewelry Kenya Her Kingdom",
  "Heritage Day 2026 jewelry Kenya Her Kingdom",
  "Pride Month 2026 jewelry Kenya Her Kingdom",
  "wedding season 2026 jewelry Kenya Her Kingdom",
  "graduation season 2026 jewelry Kenya Her Kingdom",
  "August holiday jewelry Kenya Her Kingdom",
  "December holiday jewelry Kenya Her Kingdom",
  "rainy season accessories Kenya Her Kingdom",
  "dry season accessories Kenya Her Kingdom",

  // ========== SOCIAL MEDIA DISCOVERY ==========
  "Her Kingdom on TikTok Kenya",
  "Her Kingdom TikTok shop Kenya",
  "Her Kingdom on Instagram Kenya",
  "Her Kingdom Instagram shop Kenya",
  "Her Kingdom reel jewelry Kenya",
  "Her Kingdom viral jewelry Kenya",
  "Her Kingdom TikTok viral earrings",
  "Her Kingdom TikTok made me buy it Kenya",
  "Her Kingdom as seen on TikTok Kenya",
  "Her Kingdom as seen on Instagram Kenya",
  "trending jewelry on Kenyan TikTok Her Kingdom",
  "jewelry haul Kenya Her Kingdom",
  "jewelry try on Her Kingdom Kenya",
  "jewelry unboxing Her Kingdom Kenya",
  "jewelry review Her Kingdom Kenya",
  "jewelry GRWM Her Kingdom Nairobi",
  "what I got from Her Kingdom",
  "Her Kingdom order vlog",
  "Her Kingdom packaging reel",
  "Her Kingdom customer TikTok review",
  "Her Kingdom influencer collab Kenya",
  "Her Kingdom content creator Kenya",
  "Her Kingdom ambassador program Kenya",
  "Her Kingdom affiliate program Kenya",
  "Her Kingdom discount code Kenya",
  "Her Kingdom promo code Kenya",
  "Her Kingdom first order discount Kenya",
  "Her Kingdom student discount Kenya",
  "Her Kingdom birthday discount Kenya",
  "Her Kingdom referral Kenya",

  // ========== CARE, LEARNING, HOW-TO ==========
  "how to clean Her Kingdom earrings",
  "how to clean Her Kingdom necklace",
  "how to store Her Kingdom jewelry",
  "how to polish Her Kingdom gold plated jewelry",
  "how to prevent tarnish Her Kingdom",
  "how to remove tarnish Her Kingdom jewelry",
  "how to take care of gold plated jewelry Kenya",
  "how to care for stainless steel jewelry Kenya",
  "how to care for silver jewelry Kenya",
  "how to clean pearl jewelry Kenya",
  "how to keep jewelry from tarnishing Kenya",
  "how to store jewelry when traveling Kenya",
  "how to avoid allergic reaction to earrings Kenya",
  "how to tell hypoallergenic jewelry Kenya",
  "how to measure ring size Kenya Her Kingdom",
  "how to measure necklace length Kenya Her Kingdom",
  "how to choose earrings for face shape Kenya",
  "how to choose necklace length for neckline Kenya",
  "how to stack rings Kenya Her Kingdom",
  "how to layer necklaces Kenya Her Kingdom",
  "how to mix gold and silver jewelry Kenya",
  "how to match jewelry to outfit Kenya",
  "how to match jewelry to skin tone Kenya",
  "how to match jewelry to makeup Kenya",
  "how to style chunky gold necklace Kenya",
  "how to style pearl earrings Kenya",
  "how to style tennis bracelet Kenya",
  "how to style hoop earrings Kenya",
  "how to style statement ring Kenya",
  "Her Kingdom jewelry care guide",
  "Her Kingdom ring size guide",
  "Her Kingdom necklace length guide",
  "Her Kingdom earring style guide",
  "Her Kingdom jewelry glossary",
  "Her Kingdom material guide Kenya",

  // ========== MATERIAL & PROPERTY INTENT ==========
  "18k gold plated jewelry Kenya Her Kingdom",
  "14k gold plated jewelry Kenya Her Kingdom",
  "gold filled jewelry Kenya Her Kingdom",
  "gold vermeil jewelry Kenya Her Kingdom",
  "rose gold plated jewelry Kenya Her Kingdom",
  "yellow gold plated jewelry Kenya Her Kingdom",
  "white gold plated jewelry Kenya Her Kingdom",
  "sterling silver 925 jewelry Kenya Her Kingdom",
  "stainless steel gold tone jewelry Kenya Her Kingdom",
  "stainless steel silver tone jewelry Kenya Her Kingdom",
  "titanium jewelry Kenya Her Kingdom",
  "brass jewelry Kenya Her Kingdom",
  "copper jewelry Kenya Her Kingdom",
  "zirconia stone jewelry Kenya Her Kingdom",
  "cubic zirconia earrings Kenya Her Kingdom",
  "freshwater pearl jewelry Kenya Her Kingdom",
  "shell pearl jewelry Kenya Her Kingdom",
  "tarnish resistant jewelry Kenya Her Kingdom",
  "waterproof jewelry Kenya Her Kingdom",
  "sweat proof jewelry Kenya Her Kingdom",
  "shower safe jewelry Kenya Her Kingdom",
  "gym safe jewelry Kenya Her Kingdom",
  "pool safe jewelry Kenya Her Kingdom",
  "beach safe jewelry Kenya Her Kingdom",
  "nickel free earrings Kenya Her Kingdom",
  "lead free jewelry Kenya Her Kingdom",
  "hypoallergenic studs Kenya Her Kingdom",
  "second ear piercing earrings Kenya Her Kingdom",
  "cartilage earrings Kenya Her Kingdom",
  "helix earrings Kenya Her Kingdom",
  "tragus earrings Kenya Her Kingdom",
  "huggie earrings Kenya Her Kingdom",
  "threader earrings Kenya Her Kingdom",
  "ear cuff Kenya Her Kingdom",
  "clip on earrings Kenya Her Kingdom",

  // ========== PROFESSIONAL / CAREER DRESSING ==========
  "office jewelry Nairobi Her Kingdom",
  "work jewelry Kenya Her Kingdom",
  "corporate jewelry Nairobi Her Kingdom",
  "jewelry for job interview Nairobi Her Kingdom",
  "jewelry for first day of work Nairobi",
  "jewelry for board meeting Kenya",
  "jewelry for investor pitch Nairobi",
  "jewelry for networking event Nairobi",
  "jewelry for conference Nairobi",
  "jewelry for workshop Nairobi",
  "jewelry for NGO worker Nairobi",
  "jewelry for lawyer Nairobi",
  "jewelry for doctor Nairobi",
  "jewelry for nurse Nairobi",
  "jewelry for teacher Nairobi",
  "jewelry for banker Nairobi",
  "jewelry for accountant Nairobi",
  "jewelry for entrepreneur Nairobi",
  "jewelry for founder Nairobi",
  "jewelry for real estate agent Nairobi",
  "jewelry for flight attendant Kenya",
  "jewelry for journalist Nairobi",
  "jewelry for news anchor Kenya",
  "jewelry for presenter Kenya",
  "jewelry for MC Nairobi",
  "jewelry for speaker Nairobi",
  "jewelry for photographer Kenya",
  "jewelry for makeup artist Nairobi",
  "jewelry for hair stylist Nairobi",
  "jewelry for fashion designer Kenya",
  "jewelry for brand manager Nairobi",
  "jewelry for marketing manager Nairobi",
  "jewelry for HR manager Nairobi",
  "jewelry for CEO Nairobi",
  "jewelry for boss lady Nairobi Her Kingdom",

  // ========== BODY / SKIN / FIT SPECIFIC ==========
  "jewelry for sensitive ears Kenya Her Kingdom",
  "jewelry for sensitive skin Kenya Her Kingdom",
  "jewelry for dark skin tone Nairobi Her Kingdom",
  "jewelry for warm skin tone Kenya Her Kingdom",
  "jewelry for cool skin tone Kenya Her Kingdom",
  "jewelry for fair skin tone Nairobi Her Kingdom",
  "jewelry for chocolate skin Nairobi Her Kingdom",
  "jewelry for caramel skin Kenya Her Kingdom",
  "jewelry for melanin Kenya Her Kingdom",
  "jewelry for short neck Kenya Her Kingdom",
  "jewelry for long neck Kenya Her Kingdom",
  "jewelry for small wrist Kenya Her Kingdom",
  "jewelry for big wrist Kenya Her Kingdom",
  "jewelry for thick fingers Kenya Her Kingdom",
  "jewelry for slim fingers Kenya Her Kingdom",
  "jewelry for round face Kenya Her Kingdom",
  "jewelry for oval face Kenya Her Kingdom",
  "jewelry for heart shaped face Kenya Her Kingdom",
  "jewelry for square face Kenya Her Kingdom",
  "jewelry for long hair Kenya Her Kingdom",
  "jewelry for short hair Kenya Her Kingdom",
  "jewelry for braids Kenya Her Kingdom",
  "jewelry for locs Kenya Her Kingdom",
  "jewelry for wig Kenya Her Kingdom",
  "jewelry for turban Kenya Her Kingdom",
  "jewelry for natural hair Kenya Her Kingdom",
  "jewelry for bald head Kenya Her Kingdom",
  "jewelry for petite Kenya Her Kingdom",
  "jewelry for tall Kenya Her Kingdom",
  "jewelry for plus size Kenya Her Kingdom",
  "jewelry for slim Kenya Her Kingdom",

  // ========== OUTFIT PAIRING INTENTS ==========
  "what to wear with gold necklace Kenya Her Kingdom",
  "what to wear with pearl necklace Kenya Her Kingdom",
  "what to wear with layered necklaces Kenya Her Kingdom",
  "what to wear with statement earrings Kenya Her Kingdom",
  "what to wear with hoop earrings Kenya Her Kingdom",
  "what to wear with drop earrings Kenya Her Kingdom",
  "what to wear with stud earrings Kenya Her Kingdom",
  "what to wear with pearl earrings Kenya Her Kingdom",
  "what to wear with gold watch Kenya Her Kingdom",
  "what to wear with silver watch Kenya Her Kingdom",
  "what to wear with tennis bracelet Kenya Her Kingdom",
  "what to wear with charm bracelet Kenya Her Kingdom",
  "what to wear with bangle Kenya Her Kingdom",
  "what to wear with anklet Kenya Her Kingdom",
  "what to wear with silk scarf Kenya Her Kingdom",
  "what jewelry with little black dress Kenya Her Kingdom",
  "what jewelry with white dress Kenya Her Kingdom",
  "what jewelry with red dress Kenya Her Kingdom",
  "what jewelry with blue dress Kenya Her Kingdom",
  "what jewelry with green dress Kenya Her Kingdom",
  "what jewelry with jeans and top Kenya Her Kingdom",
  "what jewelry with blazer Kenya Her Kingdom",
  "what jewelry with turtle neck Kenya Her Kingdom",
  "what jewelry with V neck Kenya Her Kingdom",
  "what jewelry with off shoulder Kenya Her Kingdom",
  "what jewelry with halter neck Kenya Her Kingdom",
  "what jewelry with backless dress Kenya Her Kingdom",
  "what jewelry with kitenge dress Kenya Her Kingdom",
  "what jewelry with ankara dress Kenya Her Kingdom",
  "what jewelry with leso Kenya Her Kingdom",
  "what jewelry with dera Kenya Her Kingdom",
  "what jewelry with abaya Kenya Her Kingdom",
  "what jewelry with hijab Kenya Her Kingdom",
  "what jewelry with suit Kenya Her Kingdom",
  "what jewelry with trouser suit Kenya Her Kingdom",
  "what jewelry with jumpsuit Kenya Her Kingdom",
  "what jewelry with maxi dress Kenya Her Kingdom",
  "what jewelry with midi dress Kenya Her Kingdom",

  // ========== CUSTOMER OUTCOMES / BENEFITS ==========
  "jewelry that does not turn green Kenya Her Kingdom",
  "jewelry that does not fade Kenya Her Kingdom",
  "jewelry that lasts long Kenya Her Kingdom",
  "long lasting gold plated jewelry Kenya Her Kingdom",
  "best value jewelry Kenya Her Kingdom",
  "jewelry you can shower in Kenya Her Kingdom",
  "jewelry you can swim in Kenya Her Kingdom",
  "jewelry you can sleep in Kenya Her Kingdom",
  "jewelry you can exercise in Kenya Her Kingdom",
  "everyday jewelry that does not tarnish Kenya Her Kingdom",
  "jewelry for travel that does not tarnish Kenya Her Kingdom",
  "jewelry that does not cause allergies Kenya Her Kingdom",
  "jewelry for piercings that will not infect Kenya Her Kingdom",
  "jewelry for first piercing Kenya Her Kingdom",
  "jewelry that does not cause itching Kenya Her Kingdom",
  "jewelry that does not break easily Kenya Her Kingdom",
  "durable daily wear jewelry Kenya Her Kingdom",

  // ========== PRODUCT LINE DEEP DIVES ==========
  "Her Kingdom cross necklace Kenya",
  "Her Kingdom heart necklace Kenya",
  "Her Kingdom initial necklace Kenya",
  "Her Kingdom name necklace Kenya",
  "Her Kingdom personalized necklace Kenya",
  "Her Kingdom custom necklace Kenya",
  "Her Kingdom evil eye necklace Kenya",
  "Her Kingdom butterfly necklace Kenya",
  "Her Kingdom snake chain Kenya",
  "Her Kingdom rope chain Kenya",
  "Her Kingdom cuban chain Kenya",
  "Her Kingdom figaro chain Kenya",
  "Her Kingdom box chain Kenya",
  "Her Kingdom herringbone necklace Kenya",
  "Her Kingdom paperclip chain Kenya",
  "Her Kingdom tennis necklace Kenya",
  "Her Kingdom lariat necklace Kenya",
  "Her Kingdom Y necklace Kenya",
  "Her Kingdom pendant set Kenya",
  "Her Kingdom locket Kenya",
  "Her Kingdom charm bracelet Kenya",
  "Her Kingdom tennis bracelet Kenya",
  "Her Kingdom bangle bracelet Kenya",
  "Her Kingdom cuff bracelet Kenya",
  "Her Kingdom stackable bracelets Kenya",
  "Her Kingdom beaded bracelet Kenya",
  "Her Kingdom pearl bracelet Kenya",
  "Her Kingdom anklet Kenya",
  "Her Kingdom toe ring Kenya",
  "Her Kingdom body chain Kenya",
  "Her Kingdom stud earrings Kenya",
  "Her Kingdom hoop earrings Kenya",
  "Her Kingdom huggie earrings Kenya",
  "Her Kingdom chandelier earrings Kenya",
  "Her Kingdom threader earrings Kenya",
  "Her Kingdom drop earrings Kenya",
  "Her Kingdom dangle earrings Kenya",
  "Her Kingdom statement earrings Kenya",
  "Her Kingdom pearl earrings Kenya",
  "Her Kingdom signet ring Kenya",
  "Her Kingdom stacking rings Kenya",
  "Her Kingdom cocktail ring Kenya",
  "Her Kingdom promise ring Kenya",
  "Her Kingdom engagement ring Kenya",
  "Her Kingdom wedding band Kenya",
  "Her Kingdom women watch Kenya",
  "Her Kingdom men watch Kenya",
  "Her Kingdom couple watch Kenya",
  "Her Kingdom dress watch Kenya",
  "Her Kingdom sports watch Kenya",
  "Her Kingdom tote bag Kenya",
  "Her Kingdom clutch bag Kenya",
  "Her Kingdom crossbody bag Kenya",
  "Her Kingdom shoulder bag Kenya",
  "Her Kingdom evening bag Kenya",
  "Her Kingdom mini bag Kenya",
  "Her Kingdom aviator sunglasses Kenya",
  "Her Kingdom cat eye sunglasses Kenya",
  "Her Kingdom round sunglasses Kenya",
  "Her Kingdom square sunglasses Kenya",
  "Her Kingdom oversized sunglasses Kenya",
  "Her Kingdom silk scarf Kenya",
  "Her Kingdom pashmina Kenya",
  "Her Kingdom shawl Kenya",
  "Her Kingdom signature perfume Kenya",
  "Her Kingdom travel perfume Kenya",
  "Her Kingdom floral perfume Kenya",
  "Her Kingdom oud perfume Kenya",
  "Her Kingdom gift hamper Kenya",
  "Her Kingdom jewelry bundle Kenya",
  "Her Kingdom starter set Kenya",
  "Her Kingdom everyday set Kenya",
  "Her Kingdom bridal hamper Kenya",
  "Her Kingdom birthday hamper Kenya",
  "Her Kingdom valentines hamper Kenya",
  "Her Kingdom mothers day hamper Kenya",

  // ========== COMPARE & DECIDE ==========
  "which necklace is best for wedding Kenya Her Kingdom",
  "which earrings are best for office Kenya Her Kingdom",
  "which bracelet is best for daily wear Kenya Her Kingdom",
  "which watch is best for men in Kenya Her Kingdom",
  "which watch is best for women in Kenya Her Kingdom",
  "which jewelry set is best for bride Kenya Her Kingdom",
  "which jewelry set is best for bridesmaid Kenya Her Kingdom",
  "which jewelry is best for sensitive skin Kenya Her Kingdom",
  "which jewelry is best for travel Kenya Her Kingdom",
  "which jewelry is best for gifting Kenya Her Kingdom",
  "which jewelry is best for African dresses Kenya Her Kingdom",
  "which jewelry is best for corporate Kenya Her Kingdom",
  "which jewelry is best for photoshoot Kenya Her Kingdom",
  "which color jewelry for skin tone Kenya Her Kingdom",
  "gold or silver jewelry Kenya Her Kingdom",
  "rose gold or gold Kenya Her Kingdom",
  "pearl or gold necklace Kenya Her Kingdom",
  "chain necklace or pendant Kenya Her Kingdom",
  "hoop or stud earrings Kenya Her Kingdom",
  "bangle or charm bracelet Kenya Her Kingdom",
  "watch or bracelet for gift Kenya Her Kingdom",
  "necklace or earrings as first gift Kenya Her Kingdom",
  "ring or bracelet for birthday Kenya Her Kingdom",
  "matching set or single piece Kenya Her Kingdom",
  "single strand or layered necklace Kenya Her Kingdom",
  "how to choose jewelry for bride Kenya Her Kingdom",
  "how to choose jewelry for bridesmaid Kenya Her Kingdom",
  "how to choose jewelry for MOH Kenya Her Kingdom",
  "how to choose anniversary jewelry Kenya Her Kingdom",
  "how to choose graduation jewelry Kenya Her Kingdom",

  // ========== TRUST SIGNALS / POLICY-LED ==========
  "Her Kingdom refund policy Kenya",
  "Her Kingdom exchange policy Kenya",
  "Her Kingdom return policy Kenya",
  "Her Kingdom shipping policy Kenya",
  "Her Kingdom delivery timeframe Kenya",
  "Her Kingdom warranty Kenya",
  "Her Kingdom quality guarantee Kenya",
  "Her Kingdom authenticity Kenya",
  "Her Kingdom ethically sourced jewelry Kenya",
  "Her Kingdom sustainable jewelry Kenya",
  "Her Kingdom eco friendly packaging Kenya",
  "Her Kingdom gift packaging Kenya",
  "Her Kingdom free gift wrapping Kenya",
  "Her Kingdom discreet packaging Kenya",
  "Her Kingdom secure checkout Kenya",
  "Her Kingdom secure payment Kenya",
  "Her Kingdom PayHero M-PESA Kenya",
  "Her Kingdom STK push Kenya",
  "Her Kingdom cash on delivery Nairobi",
  "Her Kingdom pay on delivery Nairobi",
  "Her Kingdom card payment Kenya",
  "Her Kingdom Visa payment Kenya",
  "Her Kingdom Mastercard payment Kenya",
  "Her Kingdom buy now pay later Kenya",
  "Her Kingdom installment jewelry Kenya",
  "Her Kingdom layby jewelry Kenya",
  "Her Kingdom free delivery over KSh 7000",
  "Her Kingdom free delivery Nairobi CBD",
  "Her Kingdom same day delivery Nairobi",
  "Her Kingdom next day delivery Kenya",
  "Her Kingdom express delivery Nairobi",

  // ========== CREATIVE / LIFESTYLE STORY INTENTS ==========
  "jewelry that tells a story Kenya Her Kingdom",
  "jewelry with meaning Kenya Her Kingdom",
  "symbolic jewelry Kenya Her Kingdom",
  "heirloom jewelry Kenya Her Kingdom",
  "milestone jewelry Kenya Her Kingdom",
  "self love jewelry Kenya Her Kingdom",
  "treat yourself jewelry Kenya Her Kingdom",
  "self gift jewelry Kenya Her Kingdom",
  "jewelry as affirmation Kenya Her Kingdom",
  "jewelry for manifestation Kenya Her Kingdom",
  "jewelry for confidence Kenya Her Kingdom",
  "jewelry for good luck Kenya Her Kingdom",
  "jewelry for protection Kenya Her Kingdom",
  "jewelry for new beginnings Kenya Her Kingdom",
  "jewelry for healing Kenya Her Kingdom",
  "jewelry for glow up Kenya Her Kingdom",
  "jewelry for my soft era Kenya Her Kingdom",
  "jewelry for my CEO era Kenya Her Kingdom",
  "jewelry for my main character era Kenya Her Kingdom",
  "jewelry for hot girl era Kenya Her Kingdom",
  "jewelry for that girl era Kenya Her Kingdom",
  "romantic jewelry Kenya Her Kingdom",
  "sentimental jewelry Kenya Her Kingdom",

  // ========== SHOPPING MOMENTS ==========
  "last minute gift Nairobi Her Kingdom",
  "same day gift Nairobi Her Kingdom",
  "emergency gift Nairobi Her Kingdom",
  "tonight gift Nairobi Her Kingdom",
  "weekend gift Nairobi Her Kingdom",
  "surprise gift Nairobi Her Kingdom",
  "anonymous gift Nairobi Her Kingdom",
  "send gift to her Nairobi Her Kingdom",
  "send gift to him Nairobi Her Kingdom",
  "send gift to office Nairobi Her Kingdom",
  "send gift to school Nairobi Her Kingdom",
  "send gift to hotel Nairobi Her Kingdom",
  "order jewelry tonight Nairobi Her Kingdom",
  "order jewelry this weekend Kenya Her Kingdom",
  "order jewelry after work Nairobi Her Kingdom",
  "order jewelry during lunch break Nairobi Her Kingdom",
  "order jewelry on payday Kenya Her Kingdom",
  "order jewelry from work Nairobi Her Kingdom",
  "order jewelry from phone Nairobi Her Kingdom",
  "order jewelry from WhatsApp Nairobi Her Kingdom",

  // ========== FINAL BRAND + SITE REINFORCERS ==========
  "Her Kingdom best online jewelry shop Nairobi herkingdom.shop",
  "Her Kingdom top jewelry store Kenya herkingdom.shop",
  "Her Kingdom trusted jewelry shop herkingdom.shop",
  "Her Kingdom new arrivals herkingdom.shop",
  "Her Kingdom sale herkingdom.shop",
  "Her Kingdom gift packages herkingdom.shop",
  "Her Kingdom bridal jewelry herkingdom.shop",
  "Her Kingdom men watches herkingdom.shop",
  "Her Kingdom handbags herkingdom.shop",
  "Her Kingdom perfume herkingdom.shop",
  "Her Kingdom sunglasses herkingdom.shop",
  "Her Kingdom scarves herkingdom.shop",
  "Her Kingdom ponchos herkingdom.shop",
  "Her Kingdom blog herkingdom.shop",
  "Her Kingdom journal herkingdom.shop",
  "Her Kingdom stories herkingdom.shop",
  "Her Kingdom lookbook herkingdom.shop",
  "Her Kingdom editorial herkingdom.shop",
  "Her Kingdom campaign herkingdom.shop",
  "Her Kingdom brand story herkingdom.shop",
  "Her Kingdom about us herkingdom.shop",
  "Her Kingdom contact us herkingdom.shop",
  "Her Kingdom FAQ herkingdom.shop",
  "Her Kingdom help center herkingdom.shop",
  "Her Kingdom customer care herkingdom.shop",
  "shop Her Kingdom on herkingdom.shop",
  "buy Her Kingdom on herkingdom.shop",
  "explore Her Kingdom on herkingdom.shop",
  "discover Her Kingdom at herkingdom.shop",
  "find Her Kingdom at herkingdom.shop",
  "order Her Kingdom jewelry at herkingdom.shop Nairobi",
  "visit Her Kingdom store herkingdom.shop",
  "the official Her Kingdom store herkingdom.shop",
  "the real Her Kingdom store herkingdom.shop",
  "Her Kingdom Nairobi shop online at herkingdom.shop",
  "Her Kingdom Kenya online shop herkingdom.shop",
  "Her Kingdom Kenya jewelry online herkingdom.shop",
  "Her Kingdom jewelry herkingdom.shop Nairobi Kenya",
  "herkingdom.shop the home of Her Kingdom jewelry",
  "herkingdom.shop best jewelry in Nairobi",
  "herkingdom.shop best jewelry in Kenya",
  "herkingdom.shop Her Kingdom best online jewelry",
  "herkingdom.shop Nairobi jewelry delivery",
  "herkingdom.shop Kenya jewelry delivery",
  "herkingdom.shop order jewelry with M-Pesa",
  "herkingdom.shop cash on delivery jewelry Nairobi",
  "herkingdom.shop wedding jewelry Nairobi",
  "herkingdom.shop bridal jewelry Kenya",
  "herkingdom.shop bridesmaid jewelry Kenya",
  "herkingdom.shop mothers day gift Kenya",
  "herkingdom.shop fathers day gift Kenya",
  "herkingdom.shop valentines gift Kenya",
  "herkingdom.shop christmas gift Kenya",
  "herkingdom.shop graduation gift Kenya",
  "herkingdom.shop birthday gift Kenya",
  "herkingdom.shop anniversary gift Kenya",
  "herkingdom.shop same day delivery Nairobi",
  "herkingdom.shop free delivery Kenya",
  "herkingdom.shop hypoallergenic jewelry Kenya",
  "herkingdom.shop waterproof jewelry Kenya",
  "herkingdom.shop tarnish free jewelry Kenya",
  "herkingdom.shop 18k gold plated jewelry Kenya",
  "herkingdom.shop stainless steel jewelry Kenya",
  "herkingdom.shop sterling silver jewelry Kenya",
  "herkingdom.shop pearl jewelry Kenya",
  "herkingdom.shop statement jewelry Kenya",
  "herkingdom.shop minimalist jewelry Kenya",
  "herkingdom.shop dainty jewelry Kenya",
  "herkingdom.shop layered jewelry Kenya",
  "herkingdom.shop stackable jewelry Kenya",
  "herkingdom.shop chunky jewelry Kenya",
  "herkingdom.shop boho jewelry Kenya",
  "herkingdom.shop y2k jewelry Kenya",
  "herkingdom.shop aesthetic jewelry Kenya",
  "herkingdom.shop trendy jewelry Kenya",
  "herkingdom.shop luxury jewelry Kenya",
  "herkingdom.shop designer jewelry Kenya",
  "herkingdom.shop African jewelry Kenya",
  "herkingdom.shop African inspired jewelry Kenya",
  "herkingdom.shop cultural jewelry Kenya",
  "herkingdom.shop traditional jewelry Kenya",
  "herkingdom.shop modern jewelry Kenya",
  "herkingdom.shop classic jewelry Kenya",
  "herkingdom.shop vintage jewelry Kenya",
  "herkingdom.shop premium jewelry Kenya",
] as const

// Comma-separated string form, suitable for embedding as a single meta keywords value.
export const INTENT_SEO_KEYWORDS_EXTRA_CSV: string = INTENT_SEO_KEYWORDS_EXTRA.join(", ")
