// Intent-based SEO keywords — Her Kingdom Jewelry (Nairobi, Kenya)
// High-intent search phrases: "where to buy", "where to get", "best outfit for",
// "best jewelry set for", "how much", "which", "what to wear", etc.
// Additive — loaded in addition to SITE_SEO.allKeywords and STATIC_SEO_KEYWORDS_1000.

export const INTENT_SEO_KEYWORDS: readonly string[] = [
  // ========== WHERE TO BUY (jewelry) ==========
  "where to buy jewelry in Nairobi",
  "where to buy jewelry Nairobi CBD",
  "where to buy jewelry in Kenya",
  "where to buy affordable jewelry in Nairobi",
  "where to buy quality jewelry in Nairobi",
  "where to buy hypoallergenic jewelry in Kenya",
  "where to buy nickel free jewelry Nairobi",
  "where to buy designer jewelry in Nairobi",
  "where to buy luxury jewelry Kenya",
  "where to buy statement jewelry Nairobi",
  "where to buy minimalist jewelry Kenya",
  "where to buy trendy jewelry Nairobi",
  "where to buy gold jewelry Nairobi",
  "where to buy silver jewelry Kenya",
  "where to buy pearl jewelry Nairobi",
  "where to buy African jewelry Nairobi",
  "where to buy wedding jewelry in Nairobi",
  "where to buy bridal jewelry Kenya",
  "where to buy engagement jewelry Nairobi",
  "where to buy matching jewelry set Nairobi",
  "where to buy jewelry online in Kenya",
  "where to buy jewelry with M-Pesa Kenya",
  "where to buy jewelry with cash on delivery Nairobi",
  "where to buy jewelry for a gift Nairobi",
  "where to buy jewelry for my girlfriend Nairobi",
  "where to buy jewelry for my wife Kenya",
  "where to buy jewelry for my mom Nairobi",
  "where to buy jewelry for birthday Kenya",
  "where to buy jewelry for valentines Kenya",
  "where to buy jewelry for anniversary Nairobi",

  // ========== WHERE TO BUY (necklaces) ==========
  "where to buy necklaces in Nairobi",
  "where to buy necklaces in Kenya",
  "where to buy gold necklaces Nairobi",
  "where to buy pendant necklaces Nairobi",
  "where to buy layered necklaces Kenya",
  "where to buy choker necklaces Nairobi",
  "where to buy pearl necklaces Kenya",
  "where to buy statement necklaces Nairobi",
  "where to buy men necklaces Nairobi",
  "where to buy chain necklaces Kenya",
  "where to buy matching necklace set Nairobi",

  // ========== WHERE TO BUY (bracelets / earrings / watches / rings) ==========
  "where to buy bracelets in Nairobi",
  "where to buy bracelets in Kenya",
  "where to buy charm bracelets Nairobi",
  "where to buy bangle bracelets Kenya",
  "where to buy stackable bracelets Nairobi",
  "where to buy earrings in Nairobi",
  "where to buy earrings in Kenya",
  "where to buy hoop earrings Nairobi",
  "where to buy stud earrings Kenya",
  "where to buy drop earrings Nairobi",
  "where to buy pearl earrings Kenya",
  "where to buy hypoallergenic earrings Nairobi",
  "where to buy huggie earrings Kenya",
  "where to buy statement earrings Nairobi",
  "where to buy watches in Nairobi",
  "where to buy watches in Kenya",
  "where to buy women watches Nairobi",
  "where to buy men watches Nairobi",
  "where to buy affordable watches Kenya",
  "where to buy luxury watches Nairobi",
  "where to buy rings Nairobi",
  "where to buy rings in Kenya",
  "where to buy engagement rings Nairobi",
  "where to buy wedding rings Kenya",

  // ========== WHERE TO BUY (accessories / gifts) ==========
  "where to buy handbags in Nairobi",
  "where to buy purses Nairobi",
  "where to buy sunglasses in Nairobi",
  "where to buy perfume Nairobi",
  "where to buy scarves Nairobi",
  "where to buy shawls Kenya",
  "where to buy gift package for her Nairobi",
  "where to buy gift package for girlfriend Nairobi",
  "where to buy gift hamper Kenya",
  "where to buy flowers and jewelry gift Nairobi",
  "where to buy birthday gift for her Nairobi",
  "where to buy valentines gift for her Kenya",
  "where to buy anniversary gift Nairobi",

  // ========== WHERE TO GET ==========
  "where to get jewelry in Nairobi",
  "where to get affordable jewelry Nairobi",
  "where to get quality jewelry Kenya",
  "where to get trendy jewelry Nairobi",
  "where to get hypoallergenic jewelry Kenya",
  "where to get necklaces in Nairobi",
  "where to get bracelets in Kenya",
  "where to get earrings in Nairobi",
  "where to get watches in Nairobi",
  "where to get wedding jewelry Kenya",
  "where to get bridal jewelry Nairobi",
  "where to get matching jewelry set in Nairobi",
  "where to get gift for girlfriend in Nairobi",
  "where to get gift for wife in Kenya",
  "where to get gift for mom Nairobi",
  "where to get gift hamper Nairobi",
  "where to get valentines gift Nairobi",
  "where to get birthday gift for her Kenya",
  "where to get anniversary gift Nairobi",
  "where to get graduation gift Kenya",
  "where to get flowers and jewelry Nairobi",
  "where to get handbags Nairobi",
  "where to get sunglasses Nairobi",
  "where to get perfume Nairobi",
  "where to get jewelry delivered in Nairobi",
  "where to get same day jewelry delivery Nairobi",

  // ========== BEST JEWELRY SET FOR ==========
  "best jewelry set for wedding in Kenya",
  "best jewelry set for bride Nairobi",
  "best jewelry set for bridesmaid Kenya",
  "best jewelry set for engagement Nairobi",
  "best jewelry set for anniversary Nairobi",
  "best jewelry set for birthday gift Kenya",
  "best jewelry set for valentines Nairobi",
  "best jewelry set for mothers day Kenya",
  "best jewelry set for graduation Nairobi",
  "best jewelry set for office wear Kenya",
  "best jewelry set for date night Nairobi",
  "best jewelry set for prom Kenya",
  "best jewelry set for party Nairobi",
  "best jewelry set for evening dress Kenya",
  "best jewelry set for traditional wedding Kenya",
  "best jewelry set for African print dress",
  "best jewelry set for white dress",
  "best jewelry set for black dress",
  "best jewelry set for red dress",
  "best jewelry set for kitenge dress",
  "best jewelry set for bride Nairobi Kenya",
  "best affordable jewelry set Nairobi",
  "best hypoallergenic jewelry set Kenya",
  "best matching jewelry set in Nairobi",
  "best gold jewelry set Kenya",
  "best silver jewelry set Nairobi",
  "best pearl jewelry set Kenya",

  // ========== BEST OUTFIT FOR (accessory pairing) ==========
  "best outfit for gold necklace",
  "best outfit for pearl necklace Kenya",
  "best outfit for layered necklace",
  "best outfit for statement earrings",
  "best outfit for hoop earrings Nairobi",
  "best outfit for charm bracelet",
  "best outfit for tennis bracelet",
  "best outfit for gold watch Kenya",
  "best outfit for silver watch",
  "best outfit for kitenge wedding Nairobi",
  "best outfit for traditional wedding Kenya",
  "best outfit for date night Nairobi",
  "best outfit for office in Nairobi",
  "best outfit for brunch Nairobi",
  "best outfit for a wedding guest Kenya",
  "best outfit for engagement party Kenya",
  "best outfit for valentines date Nairobi",
  "best outfit for mothers day brunch",
  "best outfit for birthday photoshoot Nairobi",
  "best outfit for graduation ceremony Kenya",
  "best outfit for baby shower Kenya",
  "best outfit for bridal shower Nairobi",
  "best outfit for kitenge dress with jewelry",
  "best outfit for black dress and gold jewelry",
  "best outfit for white dress with pearls",

  // ========== BEST JEWELRY FOR (use case) ==========
  "best jewelry for sensitive ears Nairobi",
  "best jewelry for sensitive skin Kenya",
  "best jewelry for everyday wear Nairobi",
  "best jewelry for office wear Kenya",
  "best jewelry for working out Nairobi",
  "best jewelry for swimming Kenya",
  "best jewelry for beach day Mombasa",
  "best jewelry for dark skin Kenya",
  "best jewelry for African skin tone",
  "best jewelry for weddings in Kenya",
  "best jewelry for traditional ceremonies Kenya",
  "best jewelry for kitenge outfit Nairobi",
  "best jewelry for small budget Nairobi",
  "best jewelry for students in Kenya",
  "best jewelry for teenage girl Nairobi",
  "best jewelry for Kenyan bride",
  "best jewelry for proposals Nairobi",
  "best jewelry for gifting in Kenya",
  "best jewelry for gifting girlfriend Nairobi",
  "best jewelry for gifting wife Kenya",
  "best jewelry for gifting mom Nairobi",
  "best jewelry for gifting sister Kenya",
  "best jewelry for Valentine's Day Nairobi",
  "best jewelry for Mother's Day Kenya",
  "best jewelry for Christmas gift Kenya",

  // ========== BEST JEWELRY SHOP / STORE ==========
  "best jewelry shop in Nairobi",
  "best jewelry store in Nairobi",
  "best jewelry shop in Kenya",
  "best jewelry store in Kenya",
  "best online jewelry shop in Kenya",
  "best jewelry shop Westlands",
  "best jewelry shop Kilimani",
  "best jewelry shop Karen",
  "best jewelry shop Kileleshwa",
  "best jewelry shop Lavington",
  "best jewelry shop Runda",
  "best jewelry shop Nairobi CBD",
  "best jewelry shop Mombasa",
  "best jewelry shop Kisumu",
  "best affordable jewelry shop in Nairobi",
  "best hypoallergenic jewelry shop Kenya",
  "best online jewelry store Nairobi",
  "top jewelry shops in Nairobi",
  "top jewelry stores in Kenya",
  "top 10 jewelry shops in Nairobi",
  "top 5 jewelry brands in Kenya",
  "most trusted jewelry shop in Nairobi",
  "legit online jewelry shop Kenya",
  "verified jewelry shop Nairobi",
  "reputable jewelry store Kenya",
  "most popular jewelry shop Nairobi",

  // ========== HOW MUCH / PRICE INTENT ==========
  "how much is jewelry in Nairobi",
  "how much do necklaces cost in Kenya",
  "how much are earrings in Nairobi",
  "how much is a jewelry set in Kenya",
  "how much is a gold necklace in Nairobi",
  "how much is a bracelet in Kenya",
  "how much is a watch in Nairobi",
  "how much is delivery for jewelry in Nairobi",
  "how much is free delivery jewelry Kenya",
  "affordable jewelry price in Kenya",
  "cheap jewelry price Nairobi",
  "jewelry price list Nairobi",
  "necklace price in Kenya",
  "earring price in Nairobi",
  "bracelet price in Kenya",
  "watch price in Nairobi",
  "jewelry set price Kenya",
  "gift package price Nairobi",
  "price of hypoallergenic earrings Kenya",

  // ========== WHICH / WHAT QUESTIONS ==========
  "which jewelry is best for sensitive skin Kenya",
  "which necklace to buy in Nairobi",
  "which earrings to buy for sensitive ears Kenya",
  "which jewelry set to buy for wedding Kenya",
  "which jewelry shop is best in Nairobi",
  "which jewelry brand is best in Kenya",
  "which jewelry goes with kitenge",
  "which jewelry to wear with black dress",
  "which jewelry to wear with white dress",
  "what jewelry to wear to a wedding in Kenya",
  "what jewelry to wear to a graduation",
  "what jewelry to wear to an office in Nairobi",
  "what jewelry to wear with kitenge",
  "what jewelry to wear with African dress",
  "what to wear with gold necklace",
  "what to wear with pearl earrings",
  "what jewelry is hypoallergenic in Kenya",
  "what is the best jewelry shop in Nairobi",
  "what jewelry is trending in Kenya",
  "what jewelry do brides wear in Kenya",

  // ========== HOW TO / CAN I ==========
  "how to buy jewelry online in Kenya",
  "how to buy jewelry with M-Pesa",
  "how to order jewelry in Nairobi",
  "how to get jewelry delivered in Nairobi",
  "how to pay for jewelry online Kenya",
  "how to track jewelry order Her Kingdom",
  "how to choose jewelry for wedding Kenya",
  "how to choose jewelry for bride Nairobi",
  "how to choose jewelry set Kenya",
  "how to care for hypoallergenic jewelry",
  "how to gift wrap jewelry Nairobi",
  "can I pay for jewelry with M-Pesa in Kenya",
  "can I get cash on delivery jewelry Nairobi",
  "can I get same day jewelry delivery Nairobi",
  "can I return jewelry Her Kingdom",

  // ========== GIFT INTENT (birthday / anniversary / valentines / mothers day / christmas) ==========
  "best birthday gift for her in Nairobi",
  "best birthday gift for girlfriend Kenya",
  "best birthday gift for wife Nairobi",
  "best birthday gift for sister Kenya",
  "best birthday gift for mom Kenya",
  "best birthday gift for best friend Nairobi",
  "best valentines gift for her Nairobi",
  "best valentines gift for girlfriend Kenya",
  "best valentines gift for wife Nairobi",
  "best valentines jewelry gift Kenya",
  "best anniversary gift for her Nairobi",
  "best anniversary gift for wife Kenya",
  "best mothers day gift in Nairobi",
  "best mothers day gift jewelry Kenya",
  "best christmas gift for her Nairobi",
  "best christmas gift jewelry Kenya",
  "best graduation gift for her Nairobi",
  "best bridal shower gift Kenya",
  "best bridesmaid gift Nairobi",
  "best engagement gift Nairobi Kenya",
  "best gift for her under 2000 Kenya",
  "best gift for her under 3000 Nairobi",
  "best gift for her under 5000 Kenya",
  "best gift for her under 10000 Nairobi",
  "best surprise gift for girlfriend Kenya",
  "romantic gift ideas for her Nairobi",
  "unique gift ideas for her Kenya",
  "thoughtful gift ideas for her Nairobi",
  "last minute gift for her Nairobi",
  "last minute valentines gift Kenya",

  // ========== LOCATION INTENT — "near me" & suburb ==========
  "jewelry shop near me Nairobi",
  "jewelry store near me Kenya",
  "best jewelry shop near me Nairobi",
  "jewelry delivery near me Nairobi",
  "online jewelry store Kenya near me",
  "jewelry Westlands near me",
  "jewelry Kilimani near me",
  "jewelry Karen near me",
  "jewelry Lavington near me",
  "jewelry Kileleshwa near me",
  "jewelry Nairobi CBD near me",
  "jewelry store Nairobi West",
  "jewelry store Nairobi South B",
  "jewelry store Nairobi South C",
  "jewelry store Eastlands Nairobi",
  "jewelry store Parklands Nairobi",
  "jewelry store Roysambu Nairobi",
  "jewelry store Kasarani Nairobi",
  "jewelry store Ruaka Nairobi",
  "jewelry store Ruiru Nairobi",
  "jewelry store Syokimau Nairobi",
  "jewelry store Ngong Road Nairobi",

  // ========== DELIVERY INTENT ==========
  "same day jewelry delivery Nairobi",
  "next day jewelry delivery Nairobi",
  "free jewelry delivery in Kenya",
  "jewelry delivery to Westlands",
  "jewelry delivery to Kilimani",
  "jewelry delivery to Karen",
  "jewelry delivery to Kileleshwa",
  "jewelry delivery to Lavington",
  "jewelry delivery to Ruaka",
  "jewelry delivery to Ruiru",
  "jewelry delivery to Thika",
  "jewelry delivery to Mombasa",
  "jewelry delivery to Kisumu",
  "jewelry delivery to Nakuru",
  "jewelry delivery to Eldoret",
  "affordable jewelry delivery Nairobi",

  // ========== BRAND + INTENT ==========
  "is Her Kingdom legit",
  "Her Kingdom reviews Kenya",
  "Her Kingdom location in Nairobi",
  "Her Kingdom WhatsApp number",
  "Her Kingdom delivery Nairobi",
  "Her Kingdom free delivery Kenya",
  "Her Kingdom M-Pesa payment",
  "Her Kingdom cash on delivery",
  "Her Kingdom sale prices",
  "Her Kingdom new arrivals this week",
  "Her Kingdom best sellers",
  "Her Kingdom hypoallergenic earrings",
  "Her Kingdom matching jewelry set",
  "Her Kingdom gift packages Nairobi",
  "Her Kingdom bridal jewelry Kenya",
  "Her Kingdom Valentine's gift set",
  "Her Kingdom Mother's Day gift",
  "Her Kingdom birthday gift set",
  "Her Kingdom anniversary gift Kenya",
  "Her Kingdom gift for girlfriend",
  "Her Kingdom gift for wife",
  "Her Kingdom gift for mom",

  // ========== STYLE / AESTHETIC INTENT ==========
  "aesthetic jewelry Nairobi",
  "aesthetic jewelry Kenya",
  "aesthetic gold jewelry Nairobi",
  "aesthetic silver jewelry Kenya",
  "dainty jewelry Nairobi",
  "dainty necklaces Kenya",
  "stackable jewelry Nairobi",
  "minimalist jewelry for everyday Kenya",
  "boho jewelry Nairobi",
  "y2k jewelry Nairobi",
  "vintage jewelry Nairobi",
  "chunky gold jewelry Nairobi",
  "chunky chain necklace Kenya",
  "waterproof jewelry Nairobi",
  "tarnish free jewelry Kenya",
  "18k gold plated jewelry Kenya",
  "stainless steel jewelry Nairobi",

  // ========== SEASONAL / EVENT INTENT ==========
  "Valentine's Day jewelry Nairobi 2026",
  "Mother's Day jewelry Kenya 2026",
  "Christmas jewelry gift Nairobi",
  "Ramadan gift jewelry Kenya",
  "Eid gift jewelry Nairobi",
  "Easter gift jewelry Kenya",
  "New Year jewelry gift Nairobi",
  "Black Friday jewelry deals Kenya",
  "wedding season jewelry Kenya",
  "graduation season jewelry Nairobi",
  "detty December jewelry Nairobi",
] as const

// Comma-separated string form, suitable for embedding as a single meta keywords value.
export const INTENT_SEO_KEYWORDS_CSV: string = INTENT_SEO_KEYWORDS.join(", ")
