// Static 1000 SEO keywords — Her Kingdom Jewelry (herkingdom.shop)
// Auto-generated comprehensive keyword list injected into every page metadata.
// Covers: brand, products, modifiers, occasions, locations, intents.

export const STATIC_SEO_KEYWORDS_1000: readonly string[] = [
  "Her Kingdom",
  "Her Kingdom Nairobi",
  "Her Kingdom Kenya",
  "herkingdom.shop",
  "Her Kingdom jewelry",
  "Her Kingdom shop",
  "Her Kingdom online",
  "Her Kingdom store",
  "Her Kingdom gifts",
  "Her Kingdom delivery",
  "Her Kingdom WhatsApp",
  "HerkingdomBabe",
  "Jewelry Nairobi",
  "buy jewelry Nairobi",
  "Jewelry shop Nairobi",
  "Jewelry Nairobi CBD",
  "buy jewelry Nairobi CBD",
  "Jewelry shop Nairobi CBD",
  "Jewelry Westlands",
  "buy jewelry Westlands",
  "Jewelry shop Westlands",
  "Jewelry Kilimani",
  "buy jewelry Kilimani",
  "Jewelry shop Kilimani",
  "Jewelry Karen",
  "buy jewelry Karen",
  "Jewelry shop Karen",
  "Jewelry Kileleshwa",
  "buy jewelry Kileleshwa",
  "Jewelry shop Kileleshwa",
  "Jewelry Lavington",
  "buy jewelry Lavington",
  "Jewelry shop Lavington",
  "Jewelry Runda",
  "buy jewelry Runda",
  "Jewelry shop Runda",
  "Jewelry Kenya",
  "buy jewelry Kenya",
  "Jewelry shop Kenya",
  "Jewelry Mombasa",
  "buy jewelry Mombasa",
  "Jewelry shop Mombasa",
  "Jewelry Kisumu",
  "buy jewelry Kisumu",
  "Jewelry shop Kisumu",
  "Jewelry Nakuru",
  "buy jewelry Nakuru",
  "Jewelry shop Nakuru",
  "Jewelry Eldoret",
  "buy jewelry Eldoret",
  "Jewelry shop Eldoret",
  "Jewelry Thika",
  "buy jewelry Thika",
  "Jewelry shop Thika",
  "Jewelry Diaspora",
  "buy jewelry Diaspora",
  "Jewelry shop Diaspora",
  "Jewelry Sets Nairobi",
  "buy jewelry sets Nairobi",
  "Jewelry Sets shop Nairobi",
  "Jewelry Sets Nairobi CBD",
  "buy jewelry sets Nairobi CBD",
  "Jewelry Sets shop Nairobi CBD",
  "Jewelry Sets Westlands",
  "buy jewelry sets Westlands",
  "Jewelry Sets shop Westlands",
  "Jewelry Sets Kilimani",
  "buy jewelry sets Kilimani",
  "Jewelry Sets shop Kilimani",
  "Jewelry Sets Karen",
  "buy jewelry sets Karen",
  "Jewelry Sets shop Karen",
  "Jewelry Sets Kileleshwa",
  "buy jewelry sets Kileleshwa",
  "Jewelry Sets shop Kileleshwa",
  "Jewelry Sets Lavington",
  "buy jewelry sets Lavington",
  "Jewelry Sets shop Lavington",
  "Jewelry Sets Runda",
  "buy jewelry sets Runda",
  "Jewelry Sets shop Runda",
  "Jewelry Sets Kenya",
  "buy jewelry sets Kenya",
  "Jewelry Sets shop Kenya",
  "Jewelry Sets Mombasa",
  "buy jewelry sets Mombasa",
  "Jewelry Sets shop Mombasa",
  "Jewelry Sets Kisumu",
  "buy jewelry sets Kisumu",
  "Jewelry Sets shop Kisumu",
  "Jewelry Sets Nakuru",
  "buy jewelry sets Nakuru",
  "Jewelry Sets shop Nakuru",
  "Jewelry Sets Eldoret",
  "buy jewelry sets Eldoret",
  "Jewelry Sets shop Eldoret",
  "Jewelry Sets Thika",
  "buy jewelry sets Thika",
  "Jewelry Sets shop Thika",
  "Jewelry Sets Diaspora",
  "buy jewelry sets Diaspora",
  "Jewelry Sets shop Diaspora",
  "Necklaces Nairobi",
  "buy necklaces Nairobi",
  "Necklaces shop Nairobi",
  "Necklaces Nairobi CBD",
  "buy necklaces Nairobi CBD",
  "Necklaces shop Nairobi CBD",
  "Necklaces Westlands",
  "buy necklaces Westlands",
  "Necklaces shop Westlands",
  "Necklaces Kilimani",
  "buy necklaces Kilimani",
  "Necklaces shop Kilimani",
  "Necklaces Karen",
  "buy necklaces Karen",
  "Necklaces shop Karen",
  "Necklaces Kileleshwa",
  "buy necklaces Kileleshwa",
  "Necklaces shop Kileleshwa",
  "Necklaces Lavington",
  "buy necklaces Lavington",
  "Necklaces shop Lavington",
  "Necklaces Runda",
  "buy necklaces Runda",
  "Necklaces shop Runda",
  "Necklaces Kenya",
  "buy necklaces Kenya",
  "Necklaces shop Kenya",
  "Necklaces Mombasa",
  "buy necklaces Mombasa",
  "Necklaces shop Mombasa",
  "Necklaces Kisumu",
  "buy necklaces Kisumu",
  "Necklaces shop Kisumu",
  "Necklaces Nakuru",
  "buy necklaces Nakuru",
  "Necklaces shop Nakuru",
  "Necklaces Eldoret",
  "buy necklaces Eldoret",
  "Necklaces shop Eldoret",
  "Necklaces Thika",
  "buy necklaces Thika",
  "Necklaces shop Thika",
  "Necklaces Diaspora",
  "buy necklaces Diaspora",
  "Necklaces shop Diaspora",
  "Pendant Necklaces Nairobi",
  "buy pendant necklaces Nairobi",
  "Pendant Necklaces shop Nairobi",
  "Pendant Necklaces Nairobi CBD",
  "buy pendant necklaces Nairobi CBD",
  "Pendant Necklaces shop Nairobi CBD",
  "Pendant Necklaces Westlands",
  "buy pendant necklaces Westlands",
  "Pendant Necklaces shop Westlands",
  "Pendant Necklaces Kilimani",
  "buy pendant necklaces Kilimani",
  "Pendant Necklaces shop Kilimani",
  "Pendant Necklaces Karen",
  "buy pendant necklaces Karen",
  "Pendant Necklaces shop Karen",
  "Pendant Necklaces Kileleshwa",
  "buy pendant necklaces Kileleshwa",
  "Pendant Necklaces shop Kileleshwa",
  "Pendant Necklaces Lavington",
  "buy pendant necklaces Lavington",
  "Pendant Necklaces shop Lavington",
  "Pendant Necklaces Runda",
  "buy pendant necklaces Runda",
  "Pendant Necklaces shop Runda",
  "Pendant Necklaces Kenya",
  "buy pendant necklaces Kenya",
  "Pendant Necklaces shop Kenya",
  "Pendant Necklaces Mombasa",
  "buy pendant necklaces Mombasa",
  "Pendant Necklaces shop Mombasa",
  "Pendant Necklaces Kisumu",
  "buy pendant necklaces Kisumu",
  "Pendant Necklaces shop Kisumu",
  "Pendant Necklaces Nakuru",
  "buy pendant necklaces Nakuru",
  "Pendant Necklaces shop Nakuru",
  "Pendant Necklaces Eldoret",
  "buy pendant necklaces Eldoret",
  "Pendant Necklaces shop Eldoret",
  "Pendant Necklaces Thika",
  "buy pendant necklaces Thika",
  "Pendant Necklaces shop Thika",
  "Pendant Necklaces Diaspora",
  "buy pendant necklaces Diaspora",
  "Pendant Necklaces shop Diaspora",
  "Layered Necklaces Nairobi",
  "buy layered necklaces Nairobi",
  "Layered Necklaces shop Nairobi",
  "Layered Necklaces Nairobi CBD",
  "buy layered necklaces Nairobi CBD",
  "Layered Necklaces shop Nairobi CBD",
  "Layered Necklaces Westlands",
  "buy layered necklaces Westlands",
  "Layered Necklaces shop Westlands",
  "Layered Necklaces Kilimani",
  "buy layered necklaces Kilimani",
  "Layered Necklaces shop Kilimani",
  "Layered Necklaces Karen",
  "buy layered necklaces Karen",
  "Layered Necklaces shop Karen",
  "Layered Necklaces Kileleshwa",
  "buy layered necklaces Kileleshwa",
  "Layered Necklaces shop Kileleshwa",
  "Layered Necklaces Lavington",
  "buy layered necklaces Lavington",
  "Layered Necklaces shop Lavington",
  "Layered Necklaces Runda",
  "buy layered necklaces Runda",
  "Layered Necklaces shop Runda",
  "Layered Necklaces Kenya",
  "buy layered necklaces Kenya",
  "Layered Necklaces shop Kenya",
  "Layered Necklaces Mombasa",
  "buy layered necklaces Mombasa",
  "Layered Necklaces shop Mombasa",
  "Layered Necklaces Kisumu",
  "buy layered necklaces Kisumu",
  "Layered Necklaces shop Kisumu",
  "Layered Necklaces Nakuru",
  "buy layered necklaces Nakuru",
  "Layered Necklaces shop Nakuru",
  "Layered Necklaces Eldoret",
  "buy layered necklaces Eldoret",
  "Layered Necklaces shop Eldoret",
  "Layered Necklaces Thika",
  "buy layered necklaces Thika",
  "Layered Necklaces shop Thika",
  "Layered Necklaces Diaspora",
  "buy layered necklaces Diaspora",
  "Layered Necklaces shop Diaspora",
  "Choker Necklaces Nairobi",
  "buy choker necklaces Nairobi",
  "Choker Necklaces shop Nairobi",
  "Choker Necklaces Nairobi CBD",
  "buy choker necklaces Nairobi CBD",
  "Choker Necklaces shop Nairobi CBD",
  "Choker Necklaces Westlands",
  "buy choker necklaces Westlands",
  "Choker Necklaces shop Westlands",
  "Choker Necklaces Kilimani",
  "buy choker necklaces Kilimani",
  "Choker Necklaces shop Kilimani",
  "Choker Necklaces Karen",
  "buy choker necklaces Karen",
  "Choker Necklaces shop Karen",
  "Choker Necklaces Kileleshwa",
  "buy choker necklaces Kileleshwa",
  "Choker Necklaces shop Kileleshwa",
  "Choker Necklaces Lavington",
  "buy choker necklaces Lavington",
  "Choker Necklaces shop Lavington",
  "Choker Necklaces Runda",
  "buy choker necklaces Runda",
  "Choker Necklaces shop Runda",
  "Choker Necklaces Kenya",
  "buy choker necklaces Kenya",
  "Choker Necklaces shop Kenya",
  "Choker Necklaces Mombasa",
  "buy choker necklaces Mombasa",
  "Choker Necklaces shop Mombasa",
  "Choker Necklaces Kisumu",
  "buy choker necklaces Kisumu",
  "Choker Necklaces shop Kisumu",
  "Choker Necklaces Nakuru",
  "buy choker necklaces Nakuru",
  "Choker Necklaces shop Nakuru",
  "Choker Necklaces Eldoret",
  "buy choker necklaces Eldoret",
  "Choker Necklaces shop Eldoret",
  "Choker Necklaces Thika",
  "buy choker necklaces Thika",
  "Choker Necklaces shop Thika",
  "Choker Necklaces Diaspora",
  "buy choker necklaces Diaspora",
  "Choker Necklaces shop Diaspora",
  "Chain Necklaces Nairobi",
  "buy chain necklaces Nairobi",
  "Chain Necklaces shop Nairobi",
  "Chain Necklaces Nairobi CBD",
  "buy chain necklaces Nairobi CBD",
  "Chain Necklaces shop Nairobi CBD",
  "Chain Necklaces Westlands",
  "buy chain necklaces Westlands",
  "Chain Necklaces shop Westlands",
  "Chain Necklaces Kilimani",
  "buy chain necklaces Kilimani",
  "Chain Necklaces shop Kilimani",
  "Chain Necklaces Karen",
  "buy chain necklaces Karen",
  "Chain Necklaces shop Karen",
  "Chain Necklaces Kileleshwa",
  "buy chain necklaces Kileleshwa",
  "Chain Necklaces shop Kileleshwa",
  "Chain Necklaces Lavington",
  "buy chain necklaces Lavington",
  "Chain Necklaces shop Lavington",
  "Chain Necklaces Runda",
  "buy chain necklaces Runda",
  "Chain Necklaces shop Runda",
  "Chain Necklaces Kenya",
  "buy chain necklaces Kenya",
  "Chain Necklaces shop Kenya",
  "Chain Necklaces Mombasa",
  "buy chain necklaces Mombasa",
  "Chain Necklaces shop Mombasa",
  "Chain Necklaces Kisumu",
  "buy chain necklaces Kisumu",
  "Chain Necklaces shop Kisumu",
  "Chain Necklaces Nakuru",
  "buy chain necklaces Nakuru",
  "Chain Necklaces shop Nakuru",
  "Chain Necklaces Eldoret",
  "buy chain necklaces Eldoret",
  "Chain Necklaces shop Eldoret",
  "Chain Necklaces Thika",
  "buy chain necklaces Thika",
  "Chain Necklaces shop Thika",
  "Chain Necklaces Diaspora",
  "buy chain necklaces Diaspora",
  "Chain Necklaces shop Diaspora",
  "Men Necklaces Nairobi",
  "buy men necklaces Nairobi",
  "Men Necklaces shop Nairobi",
  "Men Necklaces Nairobi CBD",
  "buy men necklaces Nairobi CBD",
  "Men Necklaces shop Nairobi CBD",
  "Men Necklaces Westlands",
  "buy men necklaces Westlands",
  "Men Necklaces shop Westlands",
  "Men Necklaces Kilimani",
  "buy men necklaces Kilimani",
  "Men Necklaces shop Kilimani",
  "Men Necklaces Karen",
  "buy men necklaces Karen",
  "Men Necklaces shop Karen",
  "Men Necklaces Kileleshwa",
  "buy men necklaces Kileleshwa",
  "Men Necklaces shop Kileleshwa",
  "Men Necklaces Lavington",
  "buy men necklaces Lavington",
  "Men Necklaces shop Lavington",
  "Men Necklaces Runda",
  "buy men necklaces Runda",
  "Men Necklaces shop Runda",
  "Men Necklaces Kenya",
  "buy men necklaces Kenya",
  "Men Necklaces shop Kenya",
  "Men Necklaces Mombasa",
  "buy men necklaces Mombasa",
  "Men Necklaces shop Mombasa",
  "Men Necklaces Kisumu",
  "buy men necklaces Kisumu",
  "Men Necklaces shop Kisumu",
  "Men Necklaces Nakuru",
  "buy men necklaces Nakuru",
  "Men Necklaces shop Nakuru",
  "Men Necklaces Eldoret",
  "buy men necklaces Eldoret",
  "Men Necklaces shop Eldoret",
  "Men Necklaces Thika",
  "buy men necklaces Thika",
  "Men Necklaces shop Thika",
  "Men Necklaces Diaspora",
  "buy men necklaces Diaspora",
  "Men Necklaces shop Diaspora",
  "Bracelets Nairobi",
  "buy bracelets Nairobi",
  "Bracelets shop Nairobi",
  "Bracelets Nairobi CBD",
  "buy bracelets Nairobi CBD",
  "Bracelets shop Nairobi CBD",
  "Bracelets Westlands",
  "buy bracelets Westlands",
  "Bracelets shop Westlands",
  "Bracelets Kilimani",
  "buy bracelets Kilimani",
  "Bracelets shop Kilimani",
  "Bracelets Karen",
  "buy bracelets Karen",
  "Bracelets shop Karen",
  "Bracelets Kileleshwa",
  "buy bracelets Kileleshwa",
  "Bracelets shop Kileleshwa",
  "Bracelets Lavington",
  "buy bracelets Lavington",
  "Bracelets shop Lavington",
  "Bracelets Runda",
  "buy bracelets Runda",
  "Bracelets shop Runda",
  "Bracelets Kenya",
  "buy bracelets Kenya",
  "Bracelets shop Kenya",
  "Bracelets Mombasa",
  "buy bracelets Mombasa",
  "Bracelets shop Mombasa",
  "Bracelets Kisumu",
  "buy bracelets Kisumu",
  "Bracelets shop Kisumu",
  "Bracelets Nakuru",
  "buy bracelets Nakuru",
  "Bracelets shop Nakuru",
  "Bracelets Eldoret",
  "buy bracelets Eldoret",
  "Bracelets shop Eldoret",
  "Bracelets Thika",
  "buy bracelets Thika",
  "Bracelets shop Thika",
  "Bracelets Diaspora",
  "buy bracelets Diaspora",
  "Bracelets shop Diaspora",
  "Bangles Nairobi",
  "buy bangles Nairobi",
  "Bangles shop Nairobi",
  "Bangles Nairobi CBD",
  "buy bangles Nairobi CBD",
  "Bangles shop Nairobi CBD",
  "Bangles Westlands",
  "buy bangles Westlands",
  "Bangles shop Westlands",
  "Bangles Kilimani",
  "buy bangles Kilimani",
  "Bangles shop Kilimani",
  "Bangles Karen",
  "buy bangles Karen",
  "Bangles shop Karen",
  "Bangles Kileleshwa",
  "buy bangles Kileleshwa",
  "Bangles shop Kileleshwa",
  "Bangles Lavington",
  "buy bangles Lavington",
  "Bangles shop Lavington",
  "Bangles Runda",
  "buy bangles Runda",
  "Bangles shop Runda",
  "Bangles Kenya",
  "buy bangles Kenya",
  "Bangles shop Kenya",
  "Bangles Mombasa",
  "buy bangles Mombasa",
  "Bangles shop Mombasa",
  "Bangles Kisumu",
  "buy bangles Kisumu",
  "Bangles shop Kisumu",
  "Bangles Nakuru",
  "buy bangles Nakuru",
  "Bangles shop Nakuru",
  "Bangles Eldoret",
  "buy bangles Eldoret",
  "Bangles shop Eldoret",
  "Bangles Thika",
  "buy bangles Thika",
  "Bangles shop Thika",
  "Bangles Diaspora",
  "buy bangles Diaspora",
  "Bangles shop Diaspora",
  "Charm Bracelets Nairobi",
  "buy charm bracelets Nairobi",
  "Charm Bracelets shop Nairobi",
  "Charm Bracelets Nairobi CBD",
  "buy charm bracelets Nairobi CBD",
  "Charm Bracelets shop Nairobi CBD",
  "Charm Bracelets Westlands",
  "buy charm bracelets Westlands",
  "Charm Bracelets shop Westlands",
  "Charm Bracelets Kilimani",
  "buy charm bracelets Kilimani",
  "Charm Bracelets shop Kilimani",
  "Charm Bracelets Karen",
  "buy charm bracelets Karen",
  "Charm Bracelets shop Karen",
  "Charm Bracelets Kileleshwa",
  "buy charm bracelets Kileleshwa",
  "Charm Bracelets shop Kileleshwa",
  "Charm Bracelets Lavington",
  "buy charm bracelets Lavington",
  "Charm Bracelets shop Lavington",
  "Charm Bracelets Runda",
  "buy charm bracelets Runda",
  "Charm Bracelets shop Runda",
  "Charm Bracelets Kenya",
  "buy charm bracelets Kenya",
  "Charm Bracelets shop Kenya",
  "Charm Bracelets Mombasa",
  "buy charm bracelets Mombasa",
  "Charm Bracelets shop Mombasa",
  "Charm Bracelets Kisumu",
  "buy charm bracelets Kisumu",
  "Charm Bracelets shop Kisumu",
  "Charm Bracelets Nakuru",
  "buy charm bracelets Nakuru",
  "Charm Bracelets shop Nakuru",
  "Charm Bracelets Eldoret",
  "buy charm bracelets Eldoret",
  "Charm Bracelets shop Eldoret",
  "Charm Bracelets Thika",
  "buy charm bracelets Thika",
  "Charm Bracelets shop Thika",
  "Charm Bracelets Diaspora",
  "buy charm bracelets Diaspora",
  "Charm Bracelets shop Diaspora",
  "Beaded Bracelets Nairobi",
  "buy beaded bracelets Nairobi",
  "Beaded Bracelets shop Nairobi",
  "Beaded Bracelets Nairobi CBD",
  "buy beaded bracelets Nairobi CBD",
  "Beaded Bracelets shop Nairobi CBD",
  "Beaded Bracelets Westlands",
  "buy beaded bracelets Westlands",
  "Beaded Bracelets shop Westlands",
  "Beaded Bracelets Kilimani",
  "buy beaded bracelets Kilimani",
  "Beaded Bracelets shop Kilimani",
  "Beaded Bracelets Karen",
  "buy beaded bracelets Karen",
  "Beaded Bracelets shop Karen",
  "Beaded Bracelets Kileleshwa",
  "buy beaded bracelets Kileleshwa",
  "Beaded Bracelets shop Kileleshwa",
  "Beaded Bracelets Lavington",
  "buy beaded bracelets Lavington",
  "Beaded Bracelets shop Lavington",
  "Beaded Bracelets Runda",
  "buy beaded bracelets Runda",
  "Beaded Bracelets shop Runda",
  "Beaded Bracelets Kenya",
  "buy beaded bracelets Kenya",
  "Beaded Bracelets shop Kenya",
  "Beaded Bracelets Mombasa",
  "buy beaded bracelets Mombasa",
  "Beaded Bracelets shop Mombasa",
  "Beaded Bracelets Kisumu",
  "buy beaded bracelets Kisumu",
  "Beaded Bracelets shop Kisumu",
  "Beaded Bracelets Nakuru",
  "buy beaded bracelets Nakuru",
  "Beaded Bracelets shop Nakuru",
  "Beaded Bracelets Eldoret",
  "buy beaded bracelets Eldoret",
  "Beaded Bracelets shop Eldoret",
  "Beaded Bracelets Thika",
  "buy beaded bracelets Thika",
  "Beaded Bracelets shop Thika",
  "Beaded Bracelets Diaspora",
  "buy beaded bracelets Diaspora",
  "Beaded Bracelets shop Diaspora",
  "Earrings Nairobi",
  "buy earrings Nairobi",
  "Earrings shop Nairobi",
  "Earrings Nairobi CBD",
  "buy earrings Nairobi CBD",
  "Earrings shop Nairobi CBD",
  "Earrings Westlands",
  "buy earrings Westlands",
  "Earrings shop Westlands",
  "Earrings Kilimani",
  "buy earrings Kilimani",
  "Earrings shop Kilimani",
  "Earrings Karen",
  "buy earrings Karen",
  "Earrings shop Karen",
  "Earrings Kileleshwa",
  "buy earrings Kileleshwa",
  "Earrings shop Kileleshwa",
  "Earrings Lavington",
  "buy earrings Lavington",
  "Earrings shop Lavington",
  "Earrings Runda",
  "buy earrings Runda",
  "Earrings shop Runda",
  "Earrings Kenya",
  "buy earrings Kenya",
  "Earrings shop Kenya",
  "Earrings Mombasa",
  "buy earrings Mombasa",
  "Earrings shop Mombasa",
  "Earrings Kisumu",
  "buy earrings Kisumu",
  "Earrings shop Kisumu",
  "Earrings Nakuru",
  "buy earrings Nakuru",
  "Earrings shop Nakuru",
  "Earrings Eldoret",
  "buy earrings Eldoret",
  "Earrings shop Eldoret",
  "Earrings Thika",
  "buy earrings Thika",
  "Earrings shop Thika",
  "Earrings Diaspora",
  "buy earrings Diaspora",
  "Earrings shop Diaspora",
  "Stud Earrings Nairobi",
  "buy stud earrings Nairobi",
  "Stud Earrings shop Nairobi",
  "Stud Earrings Nairobi CBD",
  "buy stud earrings Nairobi CBD",
  "Stud Earrings shop Nairobi CBD",
  "Stud Earrings Westlands",
  "buy stud earrings Westlands",
  "Stud Earrings shop Westlands",
  "Stud Earrings Kilimani",
  "buy stud earrings Kilimani",
  "Stud Earrings shop Kilimani",
  "Stud Earrings Karen",
  "buy stud earrings Karen",
  "Stud Earrings shop Karen",
  "Stud Earrings Kileleshwa",
  "buy stud earrings Kileleshwa",
  "Stud Earrings shop Kileleshwa",
  "Stud Earrings Lavington",
  "buy stud earrings Lavington",
  "Stud Earrings shop Lavington",
  "Stud Earrings Runda",
  "buy stud earrings Runda",
  "Stud Earrings shop Runda",
  "Stud Earrings Kenya",
  "buy stud earrings Kenya",
  "Stud Earrings shop Kenya",
  "Stud Earrings Mombasa",
  "buy stud earrings Mombasa",
  "Stud Earrings shop Mombasa",
  "Stud Earrings Kisumu",
  "buy stud earrings Kisumu",
  "Stud Earrings shop Kisumu",
  "Stud Earrings Nakuru",
  "buy stud earrings Nakuru",
  "Stud Earrings shop Nakuru",
  "Stud Earrings Eldoret",
  "buy stud earrings Eldoret",
  "Stud Earrings shop Eldoret",
  "Stud Earrings Thika",
  "buy stud earrings Thika",
  "Stud Earrings shop Thika",
  "Stud Earrings Diaspora",
  "buy stud earrings Diaspora",
  "Stud Earrings shop Diaspora",
  "Hoop Earrings Nairobi",
  "buy hoop earrings Nairobi",
  "Hoop Earrings shop Nairobi",
  "Hoop Earrings Nairobi CBD",
  "buy hoop earrings Nairobi CBD",
  "Hoop Earrings shop Nairobi CBD",
  "Hoop Earrings Westlands",
  "buy hoop earrings Westlands",
  "Hoop Earrings shop Westlands",
  "Hoop Earrings Kilimani",
  "buy hoop earrings Kilimani",
  "Hoop Earrings shop Kilimani",
  "Hoop Earrings Karen",
  "buy hoop earrings Karen",
  "Hoop Earrings shop Karen",
  "Hoop Earrings Kileleshwa",
  "buy hoop earrings Kileleshwa",
  "Hoop Earrings shop Kileleshwa",
  "Hoop Earrings Lavington",
  "buy hoop earrings Lavington",
  "Hoop Earrings shop Lavington",
  "Hoop Earrings Runda",
  "buy hoop earrings Runda",
  "Hoop Earrings shop Runda",
  "Hoop Earrings Kenya",
  "buy hoop earrings Kenya",
  "Hoop Earrings shop Kenya",
  "Hoop Earrings Mombasa",
  "buy hoop earrings Mombasa",
  "Hoop Earrings shop Mombasa",
  "Hoop Earrings Kisumu",
  "buy hoop earrings Kisumu",
  "Hoop Earrings shop Kisumu",
  "Hoop Earrings Nakuru",
  "buy hoop earrings Nakuru",
  "Hoop Earrings shop Nakuru",
  "Hoop Earrings Eldoret",
  "buy hoop earrings Eldoret",
  "Hoop Earrings shop Eldoret",
  "Hoop Earrings Thika",
  "buy hoop earrings Thika",
  "Hoop Earrings shop Thika",
  "Hoop Earrings Diaspora",
  "buy hoop earrings Diaspora",
  "Hoop Earrings shop Diaspora",
  "Drop Earrings Nairobi",
  "buy drop earrings Nairobi",
  "Drop Earrings shop Nairobi",
  "Drop Earrings Nairobi CBD",
  "buy drop earrings Nairobi CBD",
  "Drop Earrings shop Nairobi CBD",
  "Drop Earrings Westlands",
  "buy drop earrings Westlands",
  "Drop Earrings shop Westlands",
  "Drop Earrings Kilimani",
  "buy drop earrings Kilimani",
  "Drop Earrings shop Kilimani",
  "Drop Earrings Karen",
  "buy drop earrings Karen",
  "Drop Earrings shop Karen",
  "Drop Earrings Kileleshwa",
  "buy drop earrings Kileleshwa",
  "Drop Earrings shop Kileleshwa",
  "Drop Earrings Lavington",
  "buy drop earrings Lavington",
  "Drop Earrings shop Lavington",
  "Drop Earrings Runda",
  "buy drop earrings Runda",
  "Drop Earrings shop Runda",
  "Drop Earrings Kenya",
  "buy drop earrings Kenya",
  "Drop Earrings shop Kenya",
  "Drop Earrings Mombasa",
  "buy drop earrings Mombasa",
  "Drop Earrings shop Mombasa",
  "Drop Earrings Kisumu",
  "buy drop earrings Kisumu",
  "Drop Earrings shop Kisumu",
  "Drop Earrings Nakuru",
  "buy drop earrings Nakuru",
  "Drop Earrings shop Nakuru",
  "Drop Earrings Eldoret",
  "buy drop earrings Eldoret",
  "Drop Earrings shop Eldoret",
  "Drop Earrings Thika",
  "buy drop earrings Thika",
  "Drop Earrings shop Thika",
  "Drop Earrings Diaspora",
  "buy drop earrings Diaspora",
  "Drop Earrings shop Diaspora",
  "Pearl Earrings Nairobi",
  "buy pearl earrings Nairobi",
  "Pearl Earrings shop Nairobi",
  "Pearl Earrings Nairobi CBD",
  "buy pearl earrings Nairobi CBD",
  "Pearl Earrings shop Nairobi CBD",
  "Pearl Earrings Westlands",
  "buy pearl earrings Westlands",
  "Pearl Earrings shop Westlands",
  "Pearl Earrings Kilimani",
  "buy pearl earrings Kilimani",
  "Pearl Earrings shop Kilimani",
  "Pearl Earrings Karen",
  "buy pearl earrings Karen",
  "Pearl Earrings shop Karen",
  "Pearl Earrings Kileleshwa",
  "buy pearl earrings Kileleshwa",
  "Pearl Earrings shop Kileleshwa",
  "Pearl Earrings Lavington",
  "buy pearl earrings Lavington",
  "Pearl Earrings shop Lavington",
  "Pearl Earrings Runda",
  "buy pearl earrings Runda",
  "Pearl Earrings shop Runda",
  "Pearl Earrings Kenya",
  "buy pearl earrings Kenya",
  "Pearl Earrings shop Kenya",
  "Pearl Earrings Mombasa",
  "buy pearl earrings Mombasa",
  "Pearl Earrings shop Mombasa",
  "Pearl Earrings Kisumu",
  "buy pearl earrings Kisumu",
  "Pearl Earrings shop Kisumu",
  "Pearl Earrings Nakuru",
  "buy pearl earrings Nakuru",
  "Pearl Earrings shop Nakuru",
  "Pearl Earrings Eldoret",
  "buy pearl earrings Eldoret",
  "Pearl Earrings shop Eldoret",
  "Pearl Earrings Thika",
  "buy pearl earrings Thika",
  "Pearl Earrings shop Thika",
  "Pearl Earrings Diaspora",
  "buy pearl earrings Diaspora",
  "Pearl Earrings shop Diaspora",
  "Watches Nairobi",
  "buy watches Nairobi",
  "Watches shop Nairobi",
  "Watches Nairobi CBD",
  "buy watches Nairobi CBD",
  "Watches shop Nairobi CBD",
  "Watches Westlands",
  "buy watches Westlands",
  "Watches shop Westlands",
  "Watches Kilimani",
  "buy watches Kilimani",
  "Watches shop Kilimani",
  "Watches Karen",
  "buy watches Karen",
  "Watches shop Karen",
  "Watches Kileleshwa",
  "buy watches Kileleshwa",
  "Watches shop Kileleshwa",
  "Watches Lavington",
  "buy watches Lavington",
  "Watches shop Lavington",
  "Watches Runda",
  "buy watches Runda",
  "Watches shop Runda",
  "Watches Kenya",
  "buy watches Kenya",
  "Watches shop Kenya",
  "Watches Mombasa",
  "buy watches Mombasa",
  "Watches shop Mombasa",
  "Watches Kisumu",
  "buy watches Kisumu",
  "Watches shop Kisumu",
  "Watches Nakuru",
  "buy watches Nakuru",
  "Watches shop Nakuru",
  "Watches Eldoret",
  "buy watches Eldoret",
  "Watches shop Eldoret",
  "Watches Thika",
  "buy watches Thika",
  "Watches shop Thika",
  "Watches Diaspora",
  "buy watches Diaspora",
  "Watches shop Diaspora",
  "Women Watches Nairobi",
  "buy women watches Nairobi",
  "Women Watches shop Nairobi",
  "Women Watches Nairobi CBD",
  "buy women watches Nairobi CBD",
  "Women Watches shop Nairobi CBD",
  "Women Watches Westlands",
  "buy women watches Westlands",
  "Women Watches shop Westlands",
  "Women Watches Kilimani",
  "buy women watches Kilimani",
  "Women Watches shop Kilimani",
  "Women Watches Karen",
  "buy women watches Karen",
  "Women Watches shop Karen",
  "Women Watches Kileleshwa",
  "buy women watches Kileleshwa",
  "Women Watches shop Kileleshwa",
  "Women Watches Lavington",
  "buy women watches Lavington",
  "Women Watches shop Lavington",
  "Women Watches Runda",
  "buy women watches Runda",
  "Women Watches shop Runda",
  "Women Watches Kenya",
  "buy women watches Kenya",
  "Women Watches shop Kenya",
  "Women Watches Mombasa",
  "buy women watches Mombasa",
  "Women Watches shop Mombasa",
  "Women Watches Kisumu",
  "buy women watches Kisumu",
  "Women Watches shop Kisumu",
  "Women Watches Nakuru",
  "buy women watches Nakuru",
  "Women Watches shop Nakuru",
  "Women Watches Eldoret",
  "buy women watches Eldoret",
  "Women Watches shop Eldoret",
  "Women Watches Thika",
  "buy women watches Thika",
  "Women Watches shop Thika",
  "Women Watches Diaspora",
  "buy women watches Diaspora",
  "Women Watches shop Diaspora",
  "Men Watches Nairobi",
  "buy men watches Nairobi",
  "Men Watches shop Nairobi",
  "Men Watches Nairobi CBD",
  "buy men watches Nairobi CBD",
  "Men Watches shop Nairobi CBD",
  "Men Watches Westlands",
  "buy men watches Westlands",
  "Men Watches shop Westlands",
  "Men Watches Kilimani",
  "buy men watches Kilimani",
  "Men Watches shop Kilimani",
  "Men Watches Karen",
  "buy men watches Karen",
  "Men Watches shop Karen",
  "Men Watches Kileleshwa",
  "buy men watches Kileleshwa",
  "Men Watches shop Kileleshwa",
  "Men Watches Lavington",
  "buy men watches Lavington",
  "Men Watches shop Lavington",
  "Men Watches Runda",
  "buy men watches Runda",
  "Men Watches shop Runda",
  "Men Watches Kenya",
  "buy men watches Kenya",
  "Men Watches shop Kenya",
  "Men Watches Mombasa",
  "buy men watches Mombasa",
  "Men Watches shop Mombasa",
  "Men Watches Kisumu",
  "buy men watches Kisumu",
  "Men Watches shop Kisumu",
  "Men Watches Nakuru",
  "buy men watches Nakuru",
  "Men Watches shop Nakuru",
  "Men Watches Eldoret",
  "buy men watches Eldoret",
  "Men Watches shop Eldoret",
  "Men Watches Thika",
  "buy men watches Thika",
  "Men Watches shop Thika",
  "Men Watches Diaspora",
  "buy men watches Diaspora",
  "Men Watches shop Diaspora",
  "Luxury Watches Nairobi",
  "buy luxury watches Nairobi",
  "Luxury Watches shop Nairobi",
  "Luxury Watches Nairobi CBD",
  "buy luxury watches Nairobi CBD",
  "Luxury Watches shop Nairobi CBD",
  "Luxury Watches Westlands",
  "buy luxury watches Westlands",
  "Luxury Watches shop Westlands",
  "Luxury Watches Kilimani",
  "buy luxury watches Kilimani",
  "Luxury Watches shop Kilimani",
  "Luxury Watches Karen",
  "buy luxury watches Karen",
  "Luxury Watches shop Karen",
  "Luxury Watches Kileleshwa",
  "buy luxury watches Kileleshwa",
  "Luxury Watches shop Kileleshwa",
  "Luxury Watches Lavington",
  "buy luxury watches Lavington",
  "Luxury Watches shop Lavington",
  "Luxury Watches Runda",
  "buy luxury watches Runda",
  "Luxury Watches shop Runda",
  "Luxury Watches Kenya",
  "buy luxury watches Kenya",
  "Luxury Watches shop Kenya",
  "Luxury Watches Mombasa",
  "buy luxury watches Mombasa",
  "Luxury Watches shop Mombasa",
  "Luxury Watches Kisumu",
  "buy luxury watches Kisumu",
  "Luxury Watches shop Kisumu",
  "Luxury Watches Nakuru",
  "buy luxury watches Nakuru",
  "Luxury Watches shop Nakuru",
  "Luxury Watches Eldoret",
  "buy luxury watches Eldoret",
  "Luxury Watches shop Eldoret",
  "Luxury Watches Thika",
  "buy luxury watches Thika",
  "Luxury Watches shop Thika",
  "Luxury Watches Diaspora",
  "buy luxury watches Diaspora",
  "Luxury Watches shop Diaspora",
  "Sunglasses Nairobi",
  "buy sunglasses Nairobi",
  "Sunglasses shop Nairobi",
  "Sunglasses Nairobi CBD",
  "buy sunglasses Nairobi CBD",
  "Sunglasses shop Nairobi CBD",
  "Sunglasses Westlands",
  "buy sunglasses Westlands",
  "Sunglasses shop Westlands",
  "Sunglasses Kilimani",
  "buy sunglasses Kilimani",
  "Sunglasses shop Kilimani",
  "Sunglasses Karen",
  "buy sunglasses Karen",
  "Sunglasses shop Karen",
  "Sunglasses Kileleshwa",
  "buy sunglasses Kileleshwa",
  "Sunglasses shop Kileleshwa",
  "Sunglasses Lavington",
  "buy sunglasses Lavington",
  "Sunglasses shop Lavington",
  "Sunglasses Runda",
  "buy sunglasses Runda",
  "Sunglasses shop Runda",
  "Sunglasses Kenya",
  "buy sunglasses Kenya",
  "Sunglasses shop Kenya",
  "Sunglasses Mombasa",
  "buy sunglasses Mombasa",
  "Sunglasses shop Mombasa",
  "Sunglasses Kisumu",
  "buy sunglasses Kisumu",
  "Sunglasses shop Kisumu",
  "Sunglasses Nakuru",
  "buy sunglasses Nakuru",
  "Sunglasses shop Nakuru",
  "Sunglasses Eldoret",
  "buy sunglasses Eldoret",
  "Sunglasses shop Eldoret",
  "Sunglasses Thika",
  "buy sunglasses Thika",
  "Sunglasses shop Thika",
  "Sunglasses Diaspora",
] as const

// Comma-separated string form, suitable for embedding as a single meta keywords value.
export const STATIC_SEO_KEYWORDS_1000_CSV: string = STATIC_SEO_KEYWORDS_1000.join(", ")
